create or replace function public.is_valid_menu_option_groups(value jsonb)
returns boolean
language sql
immutable
set search_path = public
as $$
  select jsonb_typeof(value) = 'array'
    and not exists (
      select 1
      from jsonb_array_elements(value) as groups(group_item)
      where jsonb_typeof(group_item) is distinct from 'object'
         or jsonb_typeof(group_item -> 'id') is distinct from 'string'
         or btrim(group_item ->> 'id') = ''
         or jsonb_typeof(group_item -> 'name') is distinct from 'string'
         or btrim(group_item ->> 'name') = ''
         or jsonb_typeof(group_item -> 'type') is distinct from 'string'
         or group_item ->> 'type' not in ('single', 'multiple')
         or (
           group_item ? 'required'
           and jsonb_typeof(group_item -> 'required') is distinct from 'boolean'
         )
         or jsonb_typeof(group_item -> 'options') is distinct from 'array'
         or jsonb_array_length(group_item -> 'options') = 0
         or exists (
          select 1
          from jsonb_array_elements(group_item -> 'options') as options(option_item)
          where jsonb_typeof(option_item) is distinct from 'object'
             or jsonb_typeof(option_item -> 'id') is distinct from 'string'
             or btrim(option_item ->> 'id') = ''
             or jsonb_typeof(option_item -> 'name') is distinct from 'string'
             or btrim(option_item ->> 'name') = ''
             or jsonb_typeof(option_item -> 'priceDelta') is distinct from 'number'
         )
    );
$$;

create sequence if not exists public.menu_items_id_seq;

create table if not exists public.menu_categories (
  id integer generated by default as identity primary key,
  label text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists menu_categories_label_unique_idx on public.menu_categories (label);
create index if not exists menu_categories_active_sort_idx on public.menu_categories (active, sort_order, id);
alter table public.menu_categories enable row level security;

create table if not exists public.menu_items (
  id integer primary key default nextval('public.menu_items_id_seq'::regclass),
  item_code text,
  name text not null,
  description text not null,
  detail text not null,
  price numeric(10, 2) not null check (price >= 0),
  category_id integer,
  image_url text not null,
  tags text[] not null default '{}',
  recommended boolean not null default false,
  sold_out boolean not null default false,
  option_groups jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter sequence public.menu_items_id_seq owned by public.menu_items.id;
select setval('public.menu_items_id_seq', greatest(coalesce((select max(id) from public.menu_items), 0), 1), true);

alter table public.menu_items alter column id set default nextval('public.menu_items_id_seq'::regclass);
alter table public.menu_items add column if not exists category_id integer;
alter table public.menu_items add column if not exists item_code text;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'menu_items'
      and column_name = 'category'
  ) then
    insert into public.menu_categories (label, sort_order, active)
    select distinct btrim(category), 1000 + row_number() over (order by btrim(category)) * 10, true
    from public.menu_items
    where nullif(btrim(category), '') is not null
    on conflict (label) do nothing;

    update public.menu_items as item
    set category_id = category.id,
        updated_at = now()
    from public.menu_categories as category
    where item.category_id is null
      and btrim(item.category) = category.label;
  end if;
end $$;

insert into public.menu_categories (label, sort_order, active)
select '未分类', 9999, true
where exists (select 1 from public.menu_items where category_id is null)
on conflict (label) do nothing;

update public.menu_items as item
set category_id = category.id,
    updated_at = now()
from public.menu_categories as category
where item.category_id is null
  and category.label = '未分类';

alter table public.menu_items alter column category_id set not null;

create index if not exists menu_items_active_sort_idx on public.menu_items (active, sort_order, id);
create index if not exists menu_items_category_id_idx on public.menu_items (category_id);
create unique index if not exists menu_items_item_code_unique_idx on public.menu_items (item_code) where item_code is not null;
create unique index if not exists menu_items_name_lower_unique_idx on public.menu_items (lower(trim(name)));

alter table public.menu_items
  drop constraint if exists menu_items_option_groups_shape_check;
alter table public.menu_items
  add constraint menu_items_option_groups_shape_check
  check (public.is_valid_menu_option_groups(option_groups));

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'menu_items_category_id_fkey'
      and conrelid = 'public.menu_items'::regclass
  ) then
    alter table public.menu_items
      add constraint menu_items_category_id_fkey
      foreign key (category_id)
      references public.menu_categories(id)
      on update restrict
      on delete restrict;
  end if;
end $$;

create table if not exists public.menu_item_translations (
  id bigint generated by default as identity primary key,
  item_id integer not null references public.menu_items(id) on delete cascade,
  lang text not null check (lang in ('en', 'th', 'vi')),
  name text not null,
  description text not null,
  detail text not null,
  category_label text,
  tags text[] not null default '{}',
  option_groups jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (item_id, lang)
);

create index if not exists menu_item_translations_item_lang_idx on public.menu_item_translations (item_id, lang);
alter table public.menu_item_translations enable row level security;
delete from public.menu_item_translations where lang = 'zh';
alter table public.menu_item_translations
  drop constraint if exists menu_item_translations_lang_check;
alter table public.menu_item_translations
  add constraint menu_item_translations_lang_check
  check (lang in ('en', 'th', 'vi'));

alter table public.menu_items drop column if exists translations;
drop index if exists public.menu_items_category_idx;
alter table public.menu_items drop column if exists category;

create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  password_hash text not null,
  display_name text not null,
  role text not null default 'admin' check (role in ('admin', 'kitchen', 'customer_service', 'delivery', 'owner', 'manager', 'staff')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users drop constraint if exists admin_users_role_check;
alter table public.admin_users
  add constraint admin_users_role_check check (role in ('admin', 'kitchen', 'customer_service', 'delivery', 'owner', 'manager', 'staff'));

create unique index if not exists admin_users_username_lower_unique_idx on public.admin_users (lower(username));
create index if not exists admin_users_active_idx on public.admin_users (active);
create index if not exists admin_users_role_idx on public.admin_users (role);
alter table public.admin_users enable row level security;

create table if not exists public.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  admin_user_id uuid not null references public.admin_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists admin_sessions_user_idx on public.admin_sessions (admin_user_id);
create index if not exists admin_sessions_expires_idx on public.admin_sessions (expires_at);
alter table public.admin_sessions enable row level security;

create table if not exists public.store_branches (
  id text primary key,
  name text not null,
  address text not null,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.store_branches (id, name, address, latitude, longitude, active, sort_order)
values
  ('pudu', 'PUDU 区', '10-12a, Jalan Metro Pudu 2, Fraser Business Park, 55200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', null, null, true, 10),
  ('cheras', 'Cheras 区', 'No 34G, Block E, Jalan 1/101c, Cheras Business Centre, 56100 Cheras, Wilayah Persekutuan Kuala Lumpur', null, null, true, 20)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  active = excluded.active,
  sort_order = excluded.sort_order,
  updated_at = now();

create index if not exists store_branches_active_sort_idx on public.store_branches (active, sort_order, id);
alter table public.store_branches enable row level security;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_no text not null unique,
  order_type text not null,
  payment_method text not null,
  customer_name text not null,
  customer_phone text not null,
  table_no text,
  delivery_address text,
  note text,
  subtotal numeric(10, 2) not null,
  delivery_fee numeric(10, 2) not null default 0,
  service_charge numeric(10, 2) not null,
  total numeric(10, 2) not null,
  status text not null default 'pending_confirm',
  payment_status text not null default 'pay_at_counter',
  payment_review_status text not null default 'not_required',
  receipt_url text,
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  notification_status text not null default 'pending',
  telegram_chat_id text,
  telegram_message_id integer,
  review_tg_chat_id text,
  review_tg_message_id integer,
  kitchen_tg_chat_id text,
  kitchen_tg_message_id integer,
  delivery_tg_chat_id text,
  delivery_tg_message_id integer,
  notified_at timestamptz,
  paid_at timestamptz,
  kitchen_started_at timestamptz,
  kitchen_completed_at timestamptz,
  kitchen_started_by uuid references public.admin_users(id),
  kitchen_completed_by uuid references public.admin_users(id),
  source_payload jsonb,
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists payment_status text not null default 'pay_at_counter';
alter table public.orders add column if not exists payment_review_status text not null default 'not_required';
alter table public.orders add column if not exists receipt_url text;
alter table public.orders add column if not exists stripe_checkout_session_id text;
alter table public.orders add column if not exists stripe_payment_intent_id text;
alter table public.orders add column if not exists telegram_chat_id text;
alter table public.orders add column if not exists telegram_message_id integer;
alter table public.orders add column if not exists review_tg_chat_id text;
alter table public.orders add column if not exists review_tg_message_id integer;
alter table public.orders add column if not exists kitchen_tg_chat_id text;
alter table public.orders add column if not exists kitchen_tg_message_id integer;
alter table public.orders add column if not exists delivery_tg_chat_id text;
alter table public.orders add column if not exists delivery_tg_message_id integer;
alter table public.orders add column if not exists notified_at timestamptz;
alter table public.orders add column if not exists paid_at timestamptz;
alter table public.orders add column if not exists kitchen_started_at timestamptz;
alter table public.orders add column if not exists kitchen_completed_at timestamptz;
alter table public.orders add column if not exists kitchen_started_by uuid references public.admin_users(id);
alter table public.orders add column if not exists kitchen_completed_by uuid references public.admin_users(id);
alter table public.orders add column if not exists user_id uuid;
alter table public.orders add column if not exists coupon_id uuid;
alter table public.orders add column if not exists discount_amount numeric(10, 2) not null default 0;
alter table public.orders add column if not exists payable_total numeric(10, 2);
alter table public.orders add column if not exists delivery_fee numeric(10, 2) not null default 0;
alter table public.orders add column if not exists payment_review_token text;
alter table public.orders add column if not exists reviewed_at timestamptz;
alter table public.orders add column if not exists last_operator_telegram_user_id text;
alter table public.orders add column if not exists last_operator_name text;
alter table public.orders add column if not exists last_status_changed_at timestamptz;
alter table public.orders add column if not exists assigned_branch_id text;
alter table public.orders add column if not exists assigned_branch_name text;
alter table public.orders add column if not exists delivery_latitude numeric(10, 7);
alter table public.orders add column if not exists delivery_longitude numeric(10, 7);
alter table public.orders add column if not exists delivery_distance_km numeric(10, 2);
alter table public.orders add column if not exists delivery_duration_min integer;
alter table public.orders add column if not exists delivery_quote_provider text;

update public.orders set payable_total = total where payable_total is null;

update public.orders set payment_method = 'stripe' where payment_method = 'online';
update public.orders set payment_method = 'tng' where payment_method = 'ewallet';
update public.orders set status = 'pending_confirm' where status in ('pending', 'awaiting_payment', 'pending_review');
update public.orders set status = 'cancelled' where status in ('payment_rejected', 'rejected');
update public.orders
set status = 'waiting_kitchen'
where status = 'pending_confirm'
  and payment_status = 'paid'
  and payment_review_status <> 'pending';

alter table public.orders drop constraint if exists orders_order_type_check;
alter table public.orders drop constraint if exists orders_payment_method_check;
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders drop constraint if exists orders_payment_status_check;
alter table public.orders drop constraint if exists orders_payment_review_status_check;
alter table public.orders drop constraint if exists orders_notification_status_check;

alter table public.orders
  add constraint orders_order_type_check check (order_type in ('dinein', 'takeaway'));

alter table public.orders
  add constraint orders_payment_method_check check (payment_method in ('cash', 'tng', 'stripe', 'wallet'));

alter table public.orders
  add constraint orders_status_check check (status in ('pending_confirm', 'waiting_kitchen', 'cooking', 'kitchen_done', 'stock_issue', 'preparing', 'delivering', 'delivered', 'completed', 'cancelled'));

alter table public.orders
  add constraint orders_payment_status_check check (payment_status in ('pay_at_counter', 'pending_review', 'awaiting_payment', 'paid'));

alter table public.orders
  add constraint orders_payment_review_status_check check (payment_review_status in ('not_required', 'pending', 'approved', 'rejected'));

alter table public.orders
  add constraint orders_notification_status_check check (notification_status in ('pending', 'sent', 'failed'));

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id text not null,
  item_code text,
  name text not null,
  unit_base_price numeric(10, 2),
  unit_options_total numeric(10, 2) not null default 0,
  unit_price numeric(10, 2) not null,
  quantity integer not null check (quantity > 0),
  line_total numeric(10, 2) not null,
  selected_options jsonb not null default '[]'::jsonb,
  item_note text,
  created_at timestamptz not null default now()
);

alter table public.order_items add column if not exists unit_base_price numeric(10, 2);
alter table public.order_items add column if not exists item_code text;
alter table public.order_items add column if not exists unit_options_total numeric(10, 2) not null default 0;
alter table public.order_items add column if not exists selected_options jsonb not null default '[]'::jsonb;
alter table public.order_items add column if not exists item_note text;

update public.order_items set unit_base_price = unit_price where unit_base_price is null;

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_kitchen_queue_idx on public.orders (status, created_at);
create index if not exists orders_kitchen_completed_idx on public.orders (kitchen_completed_at desc);
create index if not exists orders_payment_status_idx on public.orders (payment_status);
create index if not exists orders_stripe_checkout_session_idx on public.orders (stripe_checkout_session_id);
create index if not exists orders_user_id_idx on public.orders (user_id);
create index if not exists orders_coupon_id_idx on public.orders (coupon_id);
create index if not exists order_items_order_id_idx on public.order_items (order_id);

create table if not exists public.order_status_events (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  order_no text not null,
  action text not null,
  from_status text not null,
  to_status text not null,
  operator_telegram_user_id text not null,
  operator_username text,
  operator_name text,
  created_at timestamptz not null default now()
);

alter table public.order_status_events add column if not exists order_no text;
alter table public.order_status_events add column if not exists action text;
alter table public.order_status_events add column if not exists from_status text;
alter table public.order_status_events add column if not exists to_status text;
alter table public.order_status_events add column if not exists operator_telegram_user_id text;
alter table public.order_status_events add column if not exists operator_username text;
alter table public.order_status_events add column if not exists operator_name text;
alter table public.order_status_events add column if not exists created_at timestamptz not null default now();

alter table public.order_status_events drop constraint if exists order_status_events_action_check;
alter table public.order_status_events drop constraint if exists order_status_events_from_status_check;
alter table public.order_status_events drop constraint if exists order_status_events_to_status_check;

alter table public.order_status_events
  add constraint order_status_events_action_check check (action in ('send_to_kitchen', 'kitchen_start', 'kitchen_complete', 'stock_issue', 'confirm', 'start_delivery', 'delivered', 'complete', 'cancel'));

alter table public.order_status_events
  add constraint order_status_events_from_status_check check (from_status in ('pending_confirm', 'waiting_kitchen', 'cooking', 'kitchen_done', 'stock_issue', 'preparing', 'delivering', 'delivered', 'completed', 'cancelled'));

alter table public.order_status_events
  add constraint order_status_events_to_status_check check (to_status in ('pending_confirm', 'waiting_kitchen', 'cooking', 'kitchen_done', 'stock_issue', 'preparing', 'delivering', 'delivered', 'completed', 'cancelled'));

create index if not exists order_status_events_order_id_idx on public.order_status_events (order_id, created_at desc);
create index if not exists order_status_events_order_no_idx on public.order_status_events (order_no, created_at desc);
create index if not exists order_status_events_operator_idx on public.order_status_events (operator_telegram_user_id, created_at desc);

create table if not exists public.telegram_users (
  telegram_user_id text primary key,
  username text,
  first_name text,
  last_name text,
  is_admin boolean not null default false,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.telegram_users add column if not exists username text;
alter table public.telegram_users add column if not exists first_name text;
alter table public.telegram_users add column if not exists last_name text;
alter table public.telegram_users add column if not exists is_admin boolean not null default false;
alter table public.telegram_users add column if not exists first_seen_at timestamptz not null default now();
alter table public.telegram_users add column if not exists last_seen_at timestamptz not null default now();
alter table public.telegram_users add column if not exists updated_at timestamptz not null default now();

create index if not exists telegram_users_is_admin_idx on public.telegram_users (is_admin);
create index if not exists telegram_users_last_seen_idx on public.telegram_users (last_seen_at desc);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  phone text not null unique,
  display_phone text not null,
  name text,
  email text,
  birthday date,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

alter table public.users add column if not exists email text;
alter table public.users add column if not exists birthday date;

create table if not exists public.user_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.wallets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.users(id) on delete cascade,
  balance numeric(10, 2) not null default 0 check (balance >= 0),
  currency text not null default 'MYR',
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null,
  method text not null,
  amount numeric(10, 2) not null check (amount > 0),
  status text not null default 'pending',
  note text,
  receipt_url text,
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text,
  review_token text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.wallet_transactions drop constraint if exists wallet_transactions_type_check;
alter table public.wallet_transactions drop constraint if exists wallet_transactions_method_check;
alter table public.wallet_transactions drop constraint if exists wallet_transactions_status_check;

alter table public.wallet_transactions
  add constraint wallet_transactions_type_check check (type in ('recharge', 'payment', 'refund', 'adjustment'));

alter table public.wallet_transactions
  add constraint wallet_transactions_method_check check (method in ('stripe', 'tng', 'manual', 'wallet'));

alter table public.wallet_transactions
  add constraint wallet_transactions_status_check check (status in ('pending', 'succeeded', 'rejected', 'failed'));

create table if not exists public.user_addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  label text not null default '默认地址',
  recipient_name text not null,
  phone text not null,
  address text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  title text not null,
  description text,
  discount_amount numeric(10, 2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.coupons add column if not exists discount_amount numeric(10, 2) not null default 0;

create table if not exists public.user_coupons (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  coupon_id uuid not null references public.coupons(id) on delete cascade,
  status text not null default 'available',
  expires_at timestamptz,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.user_coupons add column if not exists used_at timestamptz;

alter table public.orders
  drop constraint if exists orders_user_id_fkey;

alter table public.orders
  add constraint orders_user_id_fkey foreign key (user_id) references public.users(id) on delete set null;

alter table public.orders
  drop constraint if exists orders_coupon_id_fkey;

alter table public.orders
  add constraint orders_coupon_id_fkey foreign key (coupon_id) references public.user_coupons(id) on delete set null;

create index if not exists user_sessions_token_hash_idx on public.user_sessions (token_hash);
create index if not exists user_sessions_expires_at_idx on public.user_sessions (expires_at);
create index if not exists wallets_user_id_idx on public.wallets (user_id);
create index if not exists wallet_transactions_user_id_idx on public.wallet_transactions (user_id, created_at desc);
create index if not exists wallet_transactions_status_idx on public.wallet_transactions (status);
create index if not exists user_addresses_user_id_idx on public.user_addresses (user_id);
create index if not exists user_coupons_user_id_idx on public.user_coupons (user_id);
create index if not exists orders_assigned_branch_id_idx on public.orders (assigned_branch_id);

create or replace function public.process_wallet_payment(
  user_id_input uuid,
  order_id_input uuid,
  amount_input numeric
)
returns void
language plpgsql
security definer
as $$
declare
  current_balance numeric(10, 2);
begin
  select balance
  into current_balance
  from public.wallets
  where user_id = user_id_input
  for update;

  if not found then
    raise exception 'Wallet not found';
  end if;

  if current_balance < amount_input then
    raise exception 'Insufficient wallet balance';
  end if;

  update public.wallets
  set balance = round((balance - amount_input)::numeric, 2),
      updated_at = now()
  where user_id = user_id_input;

  insert into public.wallet_transactions (user_id, type, method, amount, status, note, completed_at)
  values (user_id_input, 'payment', 'wallet', amount_input, 'succeeded', 'Order payment ' || order_id_input::text, now());
end;
$$;

create or replace function public.approve_wallet_recharge(
  transaction_id_input uuid,
  review_token_input text default null,
  stripe_session_id_input text default null,
  stripe_payment_intent_id_input text default null
)
returns void
language plpgsql
security definer
as $$
declare
  tx public.wallet_transactions%rowtype;
begin
  select *
  into tx
  from public.wallet_transactions
  where id = transaction_id_input
  for update;

  if not found then
    raise exception 'Wallet transaction not found';
  end if;

  if tx.status = 'succeeded' then
    return;
  end if;

  if tx.status <> 'pending' then
    raise exception 'Wallet transaction is not pending';
  end if;

  if review_token_input is not null and tx.review_token is distinct from review_token_input then
    raise exception 'Invalid review token';
  end if;

  update public.wallets
  set balance = round((balance + tx.amount)::numeric, 2),
      updated_at = now()
  where user_id = tx.user_id;

  if not found then
    insert into public.wallets (user_id, balance, currency)
    values (tx.user_id, tx.amount, 'MYR');
  end if;

  update public.wallet_transactions
  set status = 'succeeded',
      stripe_checkout_session_id = coalesce(stripe_session_id_input, stripe_checkout_session_id),
      stripe_payment_intent_id = coalesce(stripe_payment_intent_id_input, stripe_payment_intent_id),
      completed_at = now()
  where id = tx.id;
end;
$$;

insert into storage.buckets (id, name, public)
values ('payment-receipts', 'payment-receipts', true)
on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
values ('menu-items', 'menu-items', true)
on conflict (id) do update set public = true;

drop policy if exists "Public read payment receipts" on storage.objects;
drop policy if exists "Public read menu item images" on storage.objects;

create policy "Public read payment receipts"
on storage.objects for select
using (bucket_id = 'payment-receipts');

create policy "Public read menu item images"
on storage.objects for select
using (bucket_id = 'menu-items');

create table if not exists public.payment_settings (
  id text primary key default 'default',
  tng_account_name text not null default '',
  tng_account_number text not null default '',
  tng_qr_image_url text not null default '',
  updated_at timestamptz not null default now(),
  constraint payment_settings_singleton check (id = 'default'),
  constraint payment_settings_tng_qr_url_check check (
    tng_qr_image_url = ''
    or tng_qr_image_url ~ '^https?://'
    or tng_qr_image_url ~ '^/'
  )
);

alter table public.payment_settings enable row level security;

drop policy if exists "Payment settings are publicly readable" on public.payment_settings;
create policy "Payment settings are publicly readable"
on public.payment_settings for select
using (id = 'default');

grant select on public.payment_settings to anon, authenticated;

insert into public.payment_settings (id)
values ('default')
on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'payment-assets',
  'payment-assets',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  table_record record;
  trigger_name text;
begin
  for table_record in
    select table_schema, table_name
    from information_schema.columns
    where table_schema = 'public'
      and column_name = 'updated_at'
  loop
    trigger_name := table_record.table_name || '_set_updated_at';
    execute format('drop trigger if exists %I on %I.%I', trigger_name, table_record.table_schema, table_record.table_name);
    execute format(
      'create trigger %I before update on %I.%I for each row execute function public.set_updated_at()',
      trigger_name,
      table_record.table_schema,
      table_record.table_name
    );
  end loop;
end $$;
