create or replace function public.is_valid_menu_option_groups(value jsonb)
returns boolean
language sql
immutable
set search_path = public
as $$
  select jsonb_typeof(value) = 'array'
    and not exists (
      select 1
      from jsonb_array_elements(value) as groups(group_item)
      where jsonb_typeof(group_item) is distinct from 'object'
         or jsonb_typeof(group_item -> 'id') is distinct from 'string'
         or btrim(group_item ->> 'id') = ''
         or jsonb_typeof(group_item -> 'name') is distinct from 'string'
         or btrim(group_item ->> 'name') = ''
         or jsonb_typeof(group_item -> 'type') is distinct from 'string'
         or group_item ->> 'type' not in ('single', 'multiple')
         or (
           group_item ? 'required'
           and jsonb_typeof(group_item -> 'required') is distinct from 'boolean'
         )
         or jsonb_typeof(group_item -> 'options') is distinct from 'array'
         or jsonb_array_length(group_item -> 'options') = 0
         or exists (
          select 1
          from jsonb_array_elements(group_item -> 'options') as options(option_item)
          where jsonb_typeof(option_item) is distinct from 'object'
             or jsonb_typeof(option_item -> 'id') is distinct from 'string'
             or btrim(option_item ->> 'id') = ''
             or jsonb_typeof(option_item -> 'name') is distinct from 'string'
             or btrim(option_item ->> 'name') = ''
             or jsonb_typeof(option_item -> 'priceDelta') is distinct from 'number'
         )
    );
$$;

create sequence if not exists public.menu_items_id_seq;

create table if not exists public.menu_categories (
  id integer generated by default as identity primary key,
  label text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists menu_categories_label_unique_idx on public.menu_categories (label);
create index if not exists menu_categories_active_sort_idx on public.menu_categories (active, sort_order, id);
alter table public.menu_categories enable row level security;

create table if not exists public.menu_items (
  id integer primary key default nextval('public.menu_items_id_seq'::regclass),
  item_code text,
  name text not null,
  description text not null,
  detail text not null,
  price numeric(10, 2) not null check (price >= 0),
  category_id integer,
  image_url text not null,
  tags text[] not null default '{}',
  recommended boolean not null default false,
  sold_out boolean not null default false,
  option_groups jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter sequence public.menu_items_id_seq owned by public.menu_items.id;
select setval('public.menu_items_id_seq', greatest(coalesce((select max(id) from public.menu_items), 0), 1), true);

alter table public.menu_items alter column id set default nextval('public.menu_items_id_seq'::regclass);
alter table public.menu_items add column if not exists category_id integer;
alter table public.menu_items add column if not exists item_code text;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'menu_items'
      and column_name = 'category'
  ) then
    insert into public.menu_categories (label, sort_order, active)
    select distinct btrim(category), 1000 + row_number() over (order by btrim(category)) * 10, true
    from public.menu_items
    where nullif(btrim(category), '') is not null
    on conflict (label) do nothing;

    update public.menu_items as item
    set category_id = category.id,
        updated_at = now()
    from public.menu_categories as category
    where item.category_id is null
      and btrim(item.category) = category.label;
  end if;
end $$;

insert into public.menu_categories (label, sort_order, active)
select '未分类', 9999, true
where exists (select 1 from public.menu_items where category_id is null)
on conflict (label) do nothing;

update public.menu_items as item
set category_id = category.id,
    updated_at = now()
from public.menu_categories as category
where item.category_id is null
  and category.label = '未分类';

alter table public.menu_items alter column category_id set not null;

create index if not exists menu_items_active_sort_idx on public.menu_items (active, sort_order, id);
create index if not exists menu_items_category_id_idx on public.menu_items (category_id);
create unique index if not exists menu_items_item_code_unique_idx on public.menu_items (item_code) where item_code is not null;
create unique index if not exists menu_items_name_lower_unique_idx on public.menu_items (lower(trim(name)));

alter table public.menu_items
  drop constraint if exists menu_items_option_groups_shape_check;
alter table public.menu_items
  add constraint menu_items_option_groups_shape_check
  check (public.is_valid_menu_option_groups(option_groups));

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'menu_items_category_id_fkey'
      and conrelid = 'public.menu_items'::regclass
  ) then
    alter table public.menu_items
      add constraint menu_items_category_id_fkey
      foreign key (category_id)
      references public.menu_categories(id)
      on update restrict
      on delete restrict;
  end if;
end $$;

create table if not exists public.menu_item_translations (
  id bigint generated by default as identity primary key,
  item_id integer not null references public.menu_items(id) on delete cascade,
  lang text not null check (lang in ('en', 'th', 'vi')),
  name text not null,
  description text not null,
  detail text not null,
  category_label text,
  tags text[] not null default '{}',
  option_groups jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (item_id, lang)
);

create index if not exists menu_item_translations_item_lang_idx on public.menu_item_translations (item_id, lang);
alter table public.menu_item_translations enable row level security;
delete from public.menu_item_translations where lang = 'zh';
alter table public.menu_item_translations
  drop constraint if exists menu_item_translations_lang_check;
alter table public.menu_item_translations
  add constraint menu_item_translations_lang_check
  check (lang in ('en', 'th', 'vi'));

alter table public.menu_items drop column if exists translations;
drop index if exists public.menu_items_category_idx;
alter table public.menu_items drop column if exists category;

create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  password_hash text not null,
  display_name text not null,
  role text not null default 'admin' check (role in ('admin', 'kitchen', 'customer_service')),
  branch_scope text not null default 'assigned' check (branch_scope in ('all', 'assigned')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users drop constraint if exists admin_users_role_check;
update public.admin_users set role = 'admin' where role in ('owner', 'manager');
update public.admin_users set role = 'customer_service' where role in ('staff', 'delivery');
alter table public.admin_users
  add constraint admin_users_role_check check (role in ('admin', 'kitchen', 'customer_service'));

create unique index if not exists admin_users_username_lower_unique_idx on public.admin_users (lower(username));
create index if not exists admin_users_active_idx on public.admin_users (active);
create index if not exists admin_users_role_idx on public.admin_users (role);
alter table public.admin_users enable row level security;

create table if not exists public.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  admin_user_id uuid not null references public.admin_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists admin_sessions_user_idx on public.admin_sessions (admin_user_id);
create index if not exists admin_sessions_expires_idx on public.admin_sessions (expires_at);
alter table public.admin_sessions enable row level security;

create table if not exists public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null,
  admin_user_id uuid references public.admin_users(id) on delete set null,
  username_snapshot text not null,
  display_name_snapshot text,
  role_snapshot text check (role_snapshot is null or role_snapshot in ('admin', 'customer_service', 'kitchen')),
  branch_id_snapshot text,
  branch_scope_snapshot text check (branch_scope_snapshot is null or branch_scope_snapshot in ('all', 'assigned')),
  module text not null,
  action text not null,
  target_type text,
  target_id text,
  http_method text not null,
  request_path text not null,
  request_data jsonb,
  success boolean not null,
  status_code integer not null,
  error_message text,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists admin_audit_logs_created_idx on public.admin_audit_logs (created_at desc);
create index if not exists admin_audit_logs_admin_created_idx on public.admin_audit_logs (admin_user_id, created_at desc);
create index if not exists admin_audit_logs_module_created_idx on public.admin_audit_logs (module, created_at desc);
alter table public.admin_audit_logs enable row level security;
revoke all on table public.admin_audit_logs from public, anon, authenticated;
revoke update, delete, truncate, references, trigger on table public.admin_audit_logs from service_role;
grant select, insert on table public.admin_audit_logs to service_role;

create table if not exists public.store_branches (
  id text primary key,
  name text not null,
  address text not null,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  active boolean not null default true,
  accepting_orders boolean not null default true,
  pause_reason text,
  paused_at timestamptz,
  paused_by uuid references public.admin_users(id) on delete set null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.store_branches add column if not exists accepting_orders boolean not null default true;
alter table public.store_branches add column if not exists pause_reason text;
alter table public.store_branches add column if not exists paused_at timestamptz;
alter table public.store_branches add column if not exists paused_by uuid references public.admin_users(id) on delete set null;

insert into public.store_branches (id, name, address, latitude, longitude, active, sort_order)
values
  ('pudu', 'PUDU 区', '10-12a, Jalan Metro Pudu 2, Fraser Business Park, 55200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur', null, null, false, 10),
  ('cheras', 'Cheras 区', 'No 34G, Block E, Jalan 1/101c, Cheras Business Centre, 56100 Cheras, Wilayah Persekutuan Kuala Lumpur', null, null, true, 20)
on conflict (id) do update set
  name = excluded.name,
  address = excluded.address,
  active = excluded.active,
  sort_order = excluded.sort_order,
  updated_at = now();

create index if not exists store_branches_active_sort_idx on public.store_branches (active, sort_order, id);
alter table public.store_branches enable row level security;

create table if not exists public.branch_menu_availability (
  branch_id text not null references public.store_branches(id) on delete cascade,
  menu_item_id integer not null references public.menu_items(id) on delete cascade,
  sold_out boolean not null default false,
  updated_by uuid references public.admin_users(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (branch_id, menu_item_id)
);
create index if not exists branch_menu_availability_branch_sold_out_idx
  on public.branch_menu_availability (branch_id, sold_out, menu_item_id);
alter table public.branch_menu_availability enable row level security;

alter table public.admin_users add column if not exists assigned_branch_id text references public.store_branches(id) on delete set null;
alter table public.admin_users add column if not exists branch_scope text not null default 'assigned';
alter table public.admin_users drop constraint if exists admin_users_branch_scope_check;
alter table public.admin_users add constraint admin_users_branch_scope_check check (branch_scope in ('all', 'assigned'));
update public.admin_users set branch_scope = 'all', assigned_branch_id = null where role = 'admin';
update public.admin_users set branch_scope = 'assigned' where role = 'kitchen';
alter table public.admin_audit_logs add column if not exists branch_scope_snapshot text;
alter table public.admin_audit_logs drop constraint if exists admin_audit_logs_branch_scope_snapshot_check;
alter table public.admin_audit_logs add constraint admin_audit_logs_branch_scope_snapshot_check check (branch_scope_snapshot is null or branch_scope_snapshot in ('all', 'assigned'));
create index if not exists admin_users_assigned_branch_idx on public.admin_users (assigned_branch_id);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_no text not null unique,
  order_source text not null default 'web',
  created_by_admin_id uuid references public.admin_users(id) on delete set null,
  order_type text not null,
  payment_method text not null,
  customer_name text not null,
  customer_phone text not null,
  table_no text,
  delivery_address text,
  note text,
  subtotal numeric(10, 2) not null,
  delivery_fee numeric(10, 2) not null default 0,
  service_charge numeric(10, 2) not null,
  total numeric(10, 2) not null,
  status text not null default 'pending_confirm',
  payment_status text not null default 'pay_at_counter',
  payment_review_status text not null default 'not_required',
  receipt_url text,
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  notification_status text not null default 'pending',
  telegram_chat_id text,
  telegram_message_id integer,
  review_tg_chat_id text,
  review_tg_message_id integer,
  kitchen_tg_chat_id text,
  kitchen_tg_message_id integer,
  delivery_tg_chat_id text,
  delivery_tg_message_id integer,
  notified_at timestamptz,
  paid_at timestamptz,
  kitchen_started_at timestamptz,
  kitchen_completed_at timestamptz,
  kitchen_started_by uuid references public.admin_users(id),
  kitchen_completed_by uuid references public.admin_users(id),
  source_payload jsonb,
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists payment_status text not null default 'pay_at_counter';
alter table public.orders add column if not exists order_source text not null default 'web';
alter table public.orders add column if not exists created_by_admin_id uuid references public.admin_users(id) on delete set null;
alter table public.orders add column if not exists payment_review_status text not null default 'not_required';
alter table public.orders add column if not exists receipt_url text;
alter table public.orders add column if not exists stripe_checkout_session_id text;
alter table public.orders add column if not exists stripe_payment_intent_id text;
alter table public.orders add column if not exists telegram_chat_id text;
alter table public.orders add column if not exists telegram_message_id integer;
alter table public.orders add column if not exists review_tg_chat_id text;
alter table public.orders add column if not exists review_tg_message_id integer;
alter table public.orders add column if not exists kitchen_tg_chat_id text;
alter table public.orders add column if not exists kitchen_tg_message_id integer;
alter table public.orders add column if not exists delivery_tg_chat_id text;
alter table public.orders add column if not exists delivery_tg_message_id integer;
alter table public.orders add column if not exists notified_at timestamptz;
alter table public.orders add column if not exists paid_at timestamptz;
alter table public.orders add column if not exists kitchen_started_at timestamptz;
alter table public.orders add column if not exists kitchen_completed_at timestamptz;
alter table public.orders add column if not exists kitchen_started_by uuid references public.admin_users(id);
alter table public.orders add column if not exists kitchen_completed_by uuid references public.admin_users(id);
alter table public.orders add column if not exists user_id uuid;
alter table public.orders add column if not exists coupon_id uuid;
alter table public.orders add column if not exists discount_amount numeric(10, 2) not null default 0;
alter table public.orders add column if not exists payable_total numeric(10, 2);
alter table public.orders add column if not exists delivery_fee numeric(10, 2) not null default 0;
alter table public.orders add column if not exists payment_review_token text;
alter table public.orders add column if not exists reviewed_at timestamptz;
alter table public.orders add column if not exists last_operator_telegram_user_id text;
alter table public.orders add column if not exists last_operator_name text;
alter table public.orders add column if not exists last_status_changed_at timestamptz;
alter table public.orders add column if not exists assigned_branch_id text;
alter table public.orders add column if not exists assigned_branch_name text;
alter table public.orders add column if not exists delivery_latitude numeric(10, 7);
alter table public.orders add column if not exists delivery_longitude numeric(10, 7);
alter table public.orders add column if not exists delivery_distance_km numeric(10, 2);
alter table public.orders add column if not exists delivery_duration_min integer;
alter table public.orders add column if not exists delivery_quote_provider text;

update public.orders set payable_total = total where payable_total is null;

update public.orders set payment_method = 'stripe' where payment_method = 'online';
update public.orders set payment_method = 'tng' where payment_method = 'ewallet';
update public.orders set status = 'pending_confirm' where status in ('pending', 'awaiting_payment', 'pending_review');
update public.orders set status = 'cancelled' where status in ('payment_rejected', 'rejected');
update public.orders
set status = 'waiting_kitchen'
where status = 'pending_confirm'
  and payment_status = 'paid'
  and payment_review_status <> 'pending';

alter table public.orders drop constraint if exists orders_order_type_check;
alter table public.orders drop constraint if exists orders_payment_method_check;
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders drop constraint if exists orders_payment_status_check;
alter table public.orders drop constraint if exists orders_payment_review_status_check;
alter table public.orders drop constraint if exists orders_notification_status_check;
alter table public.orders drop constraint if exists orders_order_source_check;

alter table public.orders
  add constraint orders_order_type_check check (order_type in ('dinein', 'takeaway'));

alter table public.orders
  add constraint orders_order_source_check check (order_source in ('web', 'admin_created'));

alter table public.orders
  add constraint orders_payment_method_check check (payment_method in ('cash', 'tng', 'stripe', 'wallet'));

alter table public.orders
  add constraint orders_status_check check (status in ('pending_confirm', 'waiting_kitchen', 'cooking', 'kitchen_done', 'stock_issue', 'preparing', 'delivering', 'delivered', 'completed', 'cancelled'));

alter table public.orders
  add constraint orders_payment_status_check check (payment_status in ('pay_at_counter', 'pending_review', 'awaiting_payment', 'paid'));

alter table public.orders
  add constraint orders_payment_review_status_check check (payment_review_status in ('not_required', 'pending', 'approved', 'rejected'));

alter table public.orders
  add constraint orders_notification_status_check check (notification_status in ('pending', 'sent', 'failed'));

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id text not null,
  item_code text,
  name text not null,
  unit_base_price numeric(10, 2),
  unit_options_total numeric(10, 2) not null default 0,
  unit_price numeric(10, 2) not null,
  quantity integer not null check (quantity > 0),
  line_total numeric(10, 2) not null,
  selected_options jsonb not null default '[]'::jsonb,
  item_note text,
  created_at timestamptz not null default now()
);

alter table public.order_items add column if not exists unit_base_price numeric(10, 2);
alter table public.order_items add column if not exists item_code text;
alter table public.order_items add column if not exists unit_options_total numeric(10, 2) not null default 0;
alter table public.order_items add column if not exists selected_options jsonb not null default '[]'::jsonb;
alter table public.order_items add column if not exists item_note text;

update public.order_items set unit_base_price = unit_price where unit_base_price is null;

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_order_source_idx on public.orders (order_source);
create index if not exists orders_created_by_admin_id_idx on public.orders (created_by_admin_id);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_kitchen_queue_idx on public.orders (status, created_at);
create index if not exists orders_kitchen_completed_idx on public.orders (kitchen_completed_at desc);
create index if not exists orders_payment_status_idx on public.orders (payment_status);
create index if not exists orders_stripe_checkout_session_idx on public.orders (stripe_checkout_session_id);
create index if not exists orders_user_id_idx on public.orders (user_id);
create index if not exists orders_coupon_id_idx on public.orders (coupon_id);
create index if not exists order_items_order_id_idx on public.order_items (order_id);

create table if not exists public.delivery_tasks (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  provider text not null,
  rider_name text,
  rider_phone text,
  external_order_no text,
  status text not null default 'assigned',
  estimated_pickup_at timestamptz,
  estimated_delivery_at timestamptz,
  assigned_at timestamptz not null default now(),
  picked_up_at timestamptz,
  delivered_at timestamptz,
  cancelled_at timestamptz,
  actual_delivery_cost numeric(10, 2) not null default 0,
  assigned_by uuid references public.admin_users(id) on delete set null,
  assigned_by_name text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.delivery_tasks drop constraint if exists delivery_tasks_provider_check;
alter table public.delivery_tasks drop constraint if exists delivery_tasks_status_check;
alter table public.delivery_tasks drop constraint if exists delivery_tasks_cost_check;

alter table public.delivery_tasks
  add constraint delivery_tasks_provider_check check (provider in ('in_house', 'grab', 'lalamove', 'other'));

alter table public.delivery_tasks
  add constraint delivery_tasks_status_check check (status in ('assigned', 'picked_up', 'delivered', 'cancelled'));

alter table public.delivery_tasks
  add constraint delivery_tasks_cost_check check (actual_delivery_cost >= 0);

create index if not exists delivery_tasks_status_updated_idx on public.delivery_tasks (status, updated_at desc);
create index if not exists delivery_tasks_assigned_by_idx on public.delivery_tasks (assigned_by, assigned_at desc);

alter table public.delivery_tasks enable row level security;
revoke all on table public.delivery_tasks from anon, authenticated;
grant select, insert, update, delete on table public.delivery_tasks to service_role;

create table if not exists public.order_status_events (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  order_no text not null,
  action text not null,
  from_status text not null,
  to_status text not null,
  operator_telegram_user_id text not null,
  operator_username text,
  operator_name text,
  created_at timestamptz not null default now()
);

alter table public.order_status_events add column if not exists order_no text;
alter table public.order_status_events add column if not exists action text;
alter table public.order_status_events add column if not exists from_status text;
alter table public.order_status_events add column if not exists to_status text;
alter table public.order_status_events add column if not exists operator_telegram_user_id text;
alter table public.order_status_events add column if not exists operator_username text;
alter table public.order_status_events add column if not exists operator_name text;
alter table public.order_status_events add column if not exists created_at timestamptz not null default now();

alter table public.order_status_events drop constraint if exists order_status_events_action_check;
alter table public.order_status_events drop constraint if exists order_status_events_from_status_check;
alter table public.order_status_events drop constraint if exists order_status_events_to_status_check;

alter table public.order_status_events
  add constraint order_status_events_action_check check (action in ('send_to_kitchen', 'kitchen_start', 'kitchen_complete', 'stock_issue', 'confirm', 'start_delivery', 'delivered', 'complete', 'cancel'));

alter table public.order_status_events
  add constraint order_status_events_from_status_check check (from_status in ('pending_confirm', 'waiting_kitchen', 'cooking', 'kitchen_done', 'stock_issue', 'preparing', 'delivering', 'delivered', 'completed', 'cancelled'));

alter table public.order_status_events
  add constraint order_status_events_to_status_check check (to_status in ('pending_confirm', 'waiting_kitchen', 'cooking', 'kitchen_done', 'stock_issue', 'preparing', 'delivering', 'delivered', 'completed', 'cancelled'));

create index if not exists order_status_events_order_id_idx on public.order_status_events (order_id, created_at desc);
create index if not exists order_status_events_order_no_idx on public.order_status_events (order_no, created_at desc);
create index if not exists order_status_events_operator_idx on public.order_status_events (operator_telegram_user_id, created_at desc);

create table if not exists public.order_change_events (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  order_no text not null,
  change_type text not null,
  action text not null,
  before_data jsonb not null default '{}'::jsonb,
  after_data jsonb not null default '{}'::jsonb,
  reason text,
  related_event_id uuid references public.order_change_events(id) on delete restrict,
  created_by_admin_id uuid references public.admin_users(id) on delete set null,
  operator_name text not null,
  created_at timestamptz not null default now(),
  constraint order_change_events_change_type_check check (change_type in ('payment_method')),
  constraint order_change_events_action_check check (action in ('submitted', 'approved', 'rejected'))
);

create index if not exists order_change_events_order_created_idx
  on public.order_change_events (order_id, created_at desc);
create index if not exists order_change_events_admin_created_idx
  on public.order_change_events (created_by_admin_id, created_at desc);
create index if not exists order_change_events_related_event_idx
  on public.order_change_events (related_event_id)
  where related_event_id is not null;

alter table public.order_change_events enable row level security;
revoke all on table public.order_change_events from anon, authenticated;
revoke update, delete, truncate, references, trigger on table public.order_change_events from service_role;
grant select, insert on table public.order_change_events to service_role;

create or replace function public.submit_order_payment_change(
  order_id_input uuid,
  receipt_url_input text,
  reason_input text,
  admin_id_input uuid,
  admin_name_input text
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_order public.orders%rowtype;
  event_id uuid;
begin
  select * into current_order
  from public.orders
  where id = order_id_input
  for update;

  if not found then
    raise exception '订单不存在';
  end if;
  if current_order.order_source <> 'admin_created' then
    raise exception '只有后台代下单可以更正支付方式';
  end if;
  if current_order.status in ('completed', 'cancelled') then
    raise exception '已完成或已取消订单不能修改支付方式';
  end if;
  if current_order.payment_method <> 'cash' or current_order.payment_status <> 'pay_at_counter' then
    raise exception '当前付款状态不允许更正为转账';
  end if;
  if coalesce(length(trim(reason_input)), 0) < 2 then
    raise exception '请填写修改原因';
  end if;
  if coalesce(length(trim(receipt_url_input)), 0) = 0 then
    raise exception '请上传付款截图';
  end if;

  update public.orders
  set payment_method = 'tng',
      payment_status = 'pending_review',
      payment_review_status = 'pending',
      receipt_url = receipt_url_input,
      payment_review_token = null,
      reviewed_at = null,
      paid_at = null,
      last_operator_name = admin_name_input
  where id = current_order.id;

  insert into public.order_change_events (
    order_id,
    order_no,
    change_type,
    action,
    before_data,
    after_data,
    reason,
    created_by_admin_id,
    operator_name
  ) values (
    current_order.id,
    current_order.order_no,
    'payment_method',
    'submitted',
    jsonb_build_object(
      'payment_method', current_order.payment_method,
      'payment_status', current_order.payment_status,
      'payment_review_status', current_order.payment_review_status,
      'receipt_url', current_order.receipt_url
    ),
    jsonb_build_object(
      'payment_method', 'tng',
      'payment_status', 'pending_review',
      'payment_review_status', 'pending',
      'receipt_url', receipt_url_input
    ),
    trim(reason_input),
    admin_id_input,
    admin_name_input
  ) returning id into event_id;

  return event_id;
end;
$$;

create or replace function public.review_order_payment_change(
  order_id_input uuid,
  submitted_event_id_input uuid,
  decision_input text,
  reason_input text,
  admin_id_input uuid,
  admin_name_input text
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_order public.orders%rowtype;
  submitted_event public.order_change_events%rowtype;
  event_id uuid;
  next_action text;
  next_data jsonb;
begin
  if decision_input not in ('approve', 'reject') then
    raise exception '审核操作不正确';
  end if;
  if decision_input = 'reject' and coalesce(length(trim(reason_input)), 0) < 2 then
    raise exception '请填写拒绝原因';
  end if;

  select * into submitted_event
  from public.order_change_events
  where id = submitted_event_id_input
    and order_id = order_id_input
    and change_type = 'payment_method'
    and action = 'submitted'
  for update;

  if not found then
    raise exception '付款修改记录不存在';
  end if;
  if exists (
    select 1 from public.order_change_events
    where related_event_id = submitted_event.id
      and action in ('approved', 'rejected')
  ) then
    raise exception '该付款修改已经审核';
  end if;

  select * into current_order
  from public.orders
  where id = order_id_input
  for update;

  if not found then
    raise exception '订单不存在';
  end if;
  if current_order.payment_method <> 'tng'
    or current_order.payment_status <> 'pending_review'
    or current_order.payment_review_status <> 'pending' then
    raise exception '当前付款状态不允许审核';
  end if;

  if decision_input = 'approve' then
    update public.orders
    set payment_status = 'paid',
        payment_review_status = 'approved',
        paid_at = now(),
        reviewed_at = now(),
        last_operator_name = admin_name_input
    where id = current_order.id;
    next_action := 'approved';
    next_data := jsonb_build_object(
      'payment_method', 'tng',
      'payment_status', 'paid',
      'payment_review_status', 'approved',
      'receipt_url', current_order.receipt_url
    );
  else
    update public.orders
    set payment_method = 'cash',
        payment_status = 'pay_at_counter',
        payment_review_status = 'not_required',
        receipt_url = null,
        payment_review_token = null,
        reviewed_at = now(),
        paid_at = null,
        last_operator_name = admin_name_input
    where id = current_order.id;
    next_action := 'rejected';
    next_data := jsonb_build_object(
      'payment_method', 'cash',
      'payment_status', 'pay_at_counter',
      'payment_review_status', 'not_required',
      'receipt_url', null
    );
  end if;

  insert into public.order_change_events (
    order_id,
    order_no,
    change_type,
    action,
    before_data,
    after_data,
    reason,
    related_event_id,
    created_by_admin_id,
    operator_name
  ) values (
    current_order.id,
    current_order.order_no,
    'payment_method',
    next_action,
    jsonb_build_object(
      'payment_method', current_order.payment_method,
      'payment_status', current_order.payment_status,
      'payment_review_status', current_order.payment_review_status,
      'receipt_url', current_order.receipt_url
    ),
    next_data,
    nullif(trim(reason_input), ''),
    submitted_event.id,
    admin_id_input,
    admin_name_input
  ) returning id into event_id;

  return event_id;
end;
$$;

revoke all on function public.submit_order_payment_change(uuid, text, text, uuid, text) from public, anon, authenticated;
revoke all on function public.review_order_payment_change(uuid, uuid, text, text, uuid, text) from public, anon, authenticated;
grant execute on function public.submit_order_payment_change(uuid, text, text, uuid, text) to service_role;
grant execute on function public.review_order_payment_change(uuid, uuid, text, text, uuid, text) to service_role;

create table if not exists public.telegram_users (
  telegram_user_id text primary key,
  username text,
  first_name text,
  last_name text,
  is_admin boolean not null default false,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.telegram_users add column if not exists username text;
alter table public.telegram_users add column if not exists first_name text;
alter table public.telegram_users add column if not exists last_name text;
alter table public.telegram_users add column if not exists is_admin boolean not null default false;
alter table public.telegram_users add column if not exists first_seen_at timestamptz not null default now();
alter table public.telegram_users add column if not exists last_seen_at timestamptz not null default now();
alter table public.telegram_users add column if not exists updated_at timestamptz not null default now();

create index if not exists telegram_users_is_admin_idx on public.telegram_users (is_admin);
create index if not exists telegram_users_last_seen_idx on public.telegram_users (last_seen_at desc);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  phone text not null unique,
  display_phone text not null,
  name text,
  email text,
  birthday date,
  source text not null default 'otp',
  created_by_admin_id uuid references public.admin_users(id) on delete set null,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

alter table public.users add column if not exists email text;
alter table public.users add column if not exists birthday date;
alter table public.users add column if not exists source text not null default 'otp';
alter table public.users add column if not exists created_by_admin_id uuid references public.admin_users(id) on delete set null;

alter table public.users drop constraint if exists users_source_check;
alter table public.users
  add constraint users_source_check check (source in ('otp', 'admin_created'));

create table if not exists public.otp_challenges (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,
  phone text not null,
  display_phone text not null,
  provider_reqid text not null,
  purpose text not null check (purpose in ('login', 'update_phone')),
  request_fingerprint text not null,
  attempt_count integer not null default 0 check (attempt_count >= 0 and attempt_count <= 5),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.user_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.wallets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.users(id) on delete cascade,
  balance numeric(10, 2) not null default 0 check (balance >= 0),
  currency text not null default 'MYR',
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null,
  method text not null,
  amount numeric(10, 2) not null check (amount > 0),
  status text not null default 'pending',
  note text,
  receipt_url text,
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text,
  review_token text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.wallet_transactions add column if not exists created_by_admin_id uuid references public.admin_users(id) on delete set null;
alter table public.wallet_transactions add column if not exists balance_before numeric(10, 2);
alter table public.wallet_transactions add column if not exists balance_after numeric(10, 2);
alter table public.wallet_transactions add column if not exists recharge_channel text;
alter table public.wallet_transactions add column if not exists reference_no text;
alter table public.wallet_transactions add column if not exists idempotency_key text;

alter table public.wallet_transactions drop constraint if exists wallet_transactions_type_check;
alter table public.wallet_transactions drop constraint if exists wallet_transactions_method_check;
alter table public.wallet_transactions drop constraint if exists wallet_transactions_status_check;

alter table public.wallet_transactions
  add constraint wallet_transactions_type_check check (type in ('recharge', 'payment', 'refund', 'adjustment'));

alter table public.wallet_transactions
  add constraint wallet_transactions_method_check check (method in ('stripe', 'tng', 'manual', 'wallet'));

alter table public.wallet_transactions
  add constraint wallet_transactions_status_check check (status in ('pending', 'succeeded', 'rejected', 'failed'));

create table if not exists public.user_addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  label text not null default '默认地址',
  recipient_name text not null,
  phone text not null,
  address text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  title text not null,
  description text,
  discount_amount numeric(10, 2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.coupons add column if not exists discount_amount numeric(10, 2) not null default 0;

create table if not exists public.user_coupons (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  coupon_id uuid not null references public.coupons(id) on delete cascade,
  status text not null default 'available',
  expires_at timestamptz,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.user_coupons add column if not exists used_at timestamptz;

alter table public.orders
  drop constraint if exists orders_user_id_fkey;

alter table public.orders
  add constraint orders_user_id_fkey foreign key (user_id) references public.users(id) on delete set null;

alter table public.orders
  drop constraint if exists orders_coupon_id_fkey;

alter table public.orders
  add constraint orders_coupon_id_fkey foreign key (coupon_id) references public.user_coupons(id) on delete set null;

create index if not exists user_sessions_token_hash_idx on public.user_sessions (token_hash);
create index if not exists user_sessions_expires_at_idx on public.user_sessions (expires_at);
create index if not exists otp_challenges_phone_created_idx on public.otp_challenges (phone, created_at desc);
create index if not exists otp_challenges_fingerprint_created_idx on public.otp_challenges (request_fingerprint, created_at desc);
create index if not exists otp_challenges_expires_idx on public.otp_challenges (expires_at);
create index if not exists otp_challenges_user_created_idx on public.otp_challenges (user_id, created_at desc);
create index if not exists user_sessions_user_created_idx on public.user_sessions (user_id, created_at desc);
create index if not exists users_source_idx on public.users (source);
create index if not exists users_created_by_admin_id_idx on public.users (created_by_admin_id);
create index if not exists wallets_user_id_idx on public.wallets (user_id);
create index if not exists wallet_transactions_user_id_idx on public.wallet_transactions (user_id, created_at desc);
create index if not exists wallet_transactions_status_idx on public.wallet_transactions (status);
create index if not exists wallet_transactions_admin_idx on public.wallet_transactions (created_by_admin_id, created_at desc);
create unique index if not exists wallet_transactions_idempotency_unique_idx
  on public.wallet_transactions (idempotency_key)
  where idempotency_key is not null;
create index if not exists user_addresses_user_id_idx on public.user_addresses (user_id);
create index if not exists user_coupons_user_id_idx on public.user_coupons (user_id);
create index if not exists orders_assigned_branch_id_idx on public.orders (assigned_branch_id);

alter table public.users enable row level security;
alter table public.otp_challenges enable row level security;
alter table public.user_sessions enable row level security;
alter table public.wallets enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.user_addresses enable row level security;
alter table public.user_coupons enable row level security;

revoke all on table
  public.users,
  public.otp_challenges,
  public.user_sessions,
  public.wallets,
  public.wallet_transactions,
  public.user_addresses,
  public.user_coupons
from public, anon, authenticated;

grant select, insert, update, delete on table
  public.users,
  public.otp_challenges,
  public.user_sessions,
  public.wallets,
  public.wallet_transactions,
  public.user_addresses,
  public.user_coupons
to service_role;

create or replace function public.process_wallet_payment(
  user_id_input uuid,
  order_id_input uuid,
  amount_input numeric
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_balance numeric(10, 2);
begin
  select balance
  into current_balance
  from public.wallets
  where user_id = user_id_input
  for update;

  if not found then
    raise exception 'Wallet not found';
  end if;

  if current_balance < amount_input then
    raise exception 'Insufficient wallet balance';
  end if;

  update public.wallets
  set balance = round((balance - amount_input)::numeric, 2),
      updated_at = now()
  where user_id = user_id_input;

  insert into public.wallet_transactions (user_id, type, method, amount, status, note, completed_at)
  values (user_id_input, 'payment', 'wallet', amount_input, 'succeeded', 'Order payment ' || order_id_input::text, now());
end;
$$;

create or replace function public.approve_wallet_recharge(
  transaction_id_input uuid,
  review_token_input text default null,
  stripe_session_id_input text default null,
  stripe_payment_intent_id_input text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  tx public.wallet_transactions%rowtype;
begin
  select *
  into tx
  from public.wallet_transactions
  where id = transaction_id_input
  for update;

  if not found then
    raise exception 'Wallet transaction not found';
  end if;

  if tx.status = 'succeeded' then
    return;
  end if;

  if tx.status <> 'pending' then
    raise exception 'Wallet transaction is not pending';
  end if;

  if review_token_input is not null and tx.review_token is distinct from review_token_input then
    raise exception 'Invalid review token';
  end if;

  update public.wallets
  set balance = round((balance + tx.amount)::numeric, 2),
      updated_at = now()
  where user_id = tx.user_id;

  if not found then
    insert into public.wallets (user_id, balance, currency)
    values (tx.user_id, tx.amount, 'MYR');
  end if;

  update public.wallet_transactions
  set status = 'succeeded',
      stripe_checkout_session_id = coalesce(stripe_session_id_input, stripe_checkout_session_id),
      stripe_payment_intent_id = coalesce(stripe_payment_intent_id_input, stripe_payment_intent_id),
      completed_at = now()
  where id = tx.id;
end;
$$;

revoke all on function public.process_wallet_payment(uuid, uuid, numeric) from public, anon, authenticated;
revoke all on function public.approve_wallet_recharge(uuid, text, text, text) from public, anon, authenticated;
grant execute on function public.process_wallet_payment(uuid, uuid, numeric) to service_role;
grant execute on function public.approve_wallet_recharge(uuid, text, text, text) to service_role;

create or replace function public.admin_manual_wallet_recharge(
  user_id_input uuid,
  amount_input numeric,
  admin_id_input uuid,
  channel_input text,
  reason_input text,
  reference_no_input text default null,
  idempotency_key_input text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  wallet_before numeric(10, 2);
  wallet_after numeric(10, 2);
  transaction_id uuid;
  existing_tx public.wallet_transactions%rowtype;
begin
  if amount_input is null or amount_input < 0.01 or amount_input > 100000 then
    raise exception 'Recharge amount must be between RM 0.01 and RM 100000';
  end if;
  if channel_input not in ('cash', 'tng', 'bank', 'promotion', 'compensation', 'other') then
    raise exception 'Invalid recharge channel';
  end if;
  if length(trim(coalesce(reason_input, ''))) < 2 then
    raise exception 'Recharge reason is required';
  end if;
  if idempotency_key_input is null or length(trim(idempotency_key_input)) < 8 then
    raise exception 'Idempotency key is required';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(idempotency_key_input, 0));
  select * into existing_tx
  from public.wallet_transactions
  where idempotency_key = idempotency_key_input;

  if found then
    if existing_tx.user_id is distinct from user_id_input
      or existing_tx.amount is distinct from round(amount_input::numeric, 2)
      or existing_tx.created_by_admin_id is distinct from admin_id_input then
      raise exception 'Idempotency key has already been used';
    end if;
    return jsonb_build_object(
      'transactionId', existing_tx.id,
      'balanceBefore', existing_tx.balance_before,
      'balanceAfter', existing_tx.balance_after,
      'idempotent', true
    );
  end if;

  if not exists (select 1 from public.users where id = user_id_input) then
    raise exception 'User not found';
  end if;
  if not exists (select 1 from public.admin_users where id = admin_id_input and active = true) then
    raise exception 'Administrator not found or inactive';
  end if;

  insert into public.wallets (user_id, balance, currency)
  values (user_id_input, 0, 'MYR')
  on conflict (user_id) do nothing;

  select balance into wallet_before
  from public.wallets
  where user_id = user_id_input
  for update;

  wallet_after := round((wallet_before + amount_input)::numeric, 2);
  update public.wallets
  set balance = wallet_after,
      updated_at = now()
  where user_id = user_id_input;

  insert into public.wallet_transactions (
    user_id, type, method, amount, status, note, completed_at,
    created_by_admin_id, balance_before, balance_after, recharge_channel,
    reference_no, idempotency_key
  ) values (
    user_id_input, 'recharge', 'manual', round(amount_input::numeric, 2), 'succeeded', trim(reason_input), now(),
    admin_id_input, wallet_before, wallet_after, channel_input,
    nullif(trim(coalesce(reference_no_input, '')), ''), idempotency_key_input
  ) returning id into transaction_id;

  return jsonb_build_object(
    'transactionId', transaction_id,
    'balanceBefore', wallet_before,
    'balanceAfter', wallet_after,
    'idempotent', false
  );
end;
$$;

revoke all on function public.admin_manual_wallet_recharge(uuid, numeric, uuid, text, text, text, text) from public, anon, authenticated;
grant execute on function public.admin_manual_wallet_recharge(uuid, numeric, uuid, text, text, text, text) to service_role;

create or replace function public.admin_user_financial_summaries(user_ids_input uuid[])
returns table (
  user_id uuid,
  wallet_balance numeric,
  order_count bigint,
  total_spent numeric
)
language sql
security invoker
set search_path = ''
as $$
  select
    requested.user_id,
    coalesce(wallet.balance, 0)::numeric as wallet_balance,
    count(customer_order.id) filter (where customer_order.status <> 'cancelled') as order_count,
    coalesce(sum(coalesce(customer_order.payable_total, customer_order.total, 0)) filter (where customer_order.status <> 'cancelled'), 0)::numeric as total_spent
  from unnest(user_ids_input) as requested(user_id)
  left join public.wallets as wallet on wallet.user_id = requested.user_id
  left join public.orders as customer_order on customer_order.user_id = requested.user_id
  group by requested.user_id, wallet.balance;
$$;

revoke all on function public.admin_user_financial_summaries(uuid[]) from public, anon, authenticated;
grant execute on function public.admin_user_financial_summaries(uuid[]) to service_role;

insert into storage.buckets (id, name, public)
values ('payment-receipts', 'payment-receipts', true)
on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
values ('menu-items', 'menu-items', true)
on conflict (id) do update set public = true;

drop policy if exists "Public read payment receipts" on storage.objects;
drop policy if exists "Public read menu item images" on storage.objects;

create policy "Public read menu item images"
on storage.objects for select
using (bucket_id = 'menu-items');

create table if not exists public.payment_settings (
  id text primary key default 'default',
  tng_account_name text not null default '',
  tng_account_number text not null default '',
  tng_qr_image_url text not null default '',
  updated_at timestamptz not null default now(),
  constraint payment_settings_singleton check (id = 'default'),
  constraint payment_settings_tng_qr_url_check check (
    tng_qr_image_url = ''
    or tng_qr_image_url ~ '^https?://'
    or tng_qr_image_url ~ '^/'
  )
);

alter table public.payment_settings enable row level security;

drop policy if exists "Payment settings are publicly readable" on public.payment_settings;
create policy "Payment settings are publicly readable"
on public.payment_settings for select
using (id = 'default');

grant select on public.payment_settings to anon, authenticated;

insert into public.payment_settings (id)
values ('default')
on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'payment-assets',
  'payment-assets',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.finance_categories (
  id text primary key,
  name text not null,
  type text not null check (type in ('income', 'expense')),
  icon text not null default 'receipt',
  color text not null default 'slate',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.finance_categories enable row level security;
create index if not exists finance_categories_type_sort_idx on public.finance_categories (type, active, sort_order);

insert into public.finance_categories (id, name, type, icon, color, sort_order) values
  ('extra-sales', '额外营业收入', 'income', 'wallet', 'emerald', 10),
  ('catering', '团餐收入', 'income', 'utensils', 'emerald', 20),
  ('platform-settlement', '外卖平台结算', 'income', 'smartphone', 'blue', 30),
  ('other-income', '其他收入', 'income', 'plus', 'slate', 90),
  ('ingredients', '食材采购', 'expense', 'shopping-basket', 'orange', 10),
  ('packaging', '包装用品', 'expense', 'package', 'amber', 20),
  ('delivery-cost', '配送费用', 'expense', 'bike', 'blue', 30),
  ('utilities', '水电煤气', 'expense', 'zap', 'violet', 40),
  ('wages', '工资 / 临时工', 'expense', 'users', 'indigo', 50),
  ('maintenance', '设备维修', 'expense', 'wrench', 'rose', 60),
  ('cleaning', '清洁用品', 'expense', 'sparkles', 'cyan', 70),
  ('rent', '房租', 'expense', 'store', 'slate', 80),
  ('marketing', '营销推广', 'expense', 'megaphone', 'pink', 90),
  ('refund', '退款赔偿', 'expense', 'rotate-ccw', 'red', 100),
  ('other-expense', '其他开支', 'expense', 'more-horizontal', 'slate', 110)
on conflict (id) do update set
  name = excluded.name,
  type = excluded.type,
  icon = excluded.icon,
  color = excluded.color,
  sort_order = excluded.sort_order;

create table if not exists public.finance_transactions (
  id uuid primary key default gen_random_uuid(),
  branch_id text not null references public.store_branches(id) on delete restrict,
  transaction_type text not null check (transaction_type in ('income', 'expense')),
  category_id text not null references public.finance_categories(id) on delete restrict,
  amount numeric(12, 2) not null check (amount > 0 and amount <= 1000000),
  payment_method text not null check (payment_method in ('cash', 'tng', 'bank', 'card', 'stripe', 'wallet')),
  occurred_at timestamptz not null default now(),
  vendor_name text,
  note text,
  receipt_path text,
  status text not null default 'submitted' check (status in ('submitted', 'approved', 'voided')),
  created_by uuid not null references public.admin_users(id) on delete restrict,
  created_by_name text not null,
  approved_by uuid references public.admin_users(id) on delete set null,
  approved_at timestamptz,
  voided_by uuid references public.admin_users(id) on delete set null,
  voided_at timestamptz,
  void_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.finance_transactions enable row level security;
create index if not exists finance_transactions_branch_date_idx on public.finance_transactions (branch_id, occurred_at desc);
create index if not exists finance_transactions_status_idx on public.finance_transactions (status, occurred_at desc);
create index if not exists finance_transactions_category_idx on public.finance_transactions (category_id, occurred_at desc);
create index if not exists finance_transactions_creator_idx on public.finance_transactions (created_by, occurred_at desc);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'finance-receipts',
  'finance-receipts',
  false,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  table_record record;
  trigger_name text;
begin
  for table_record in
    select table_schema, table_name
    from information_schema.columns
    where table_schema = 'public'
      and column_name = 'updated_at'
  loop
    trigger_name := table_record.table_name || '_set_updated_at';
    execute format('drop trigger if exists %I on %I.%I', trigger_name, table_record.table_schema, table_record.table_name);
    execute format(
      'create trigger %I before update on %I.%I for each row execute function public.set_updated_at()',
      trigger_name,
      table_record.table_schema,
      table_record.table_name
    );
  end loop;
end $$;

-- Coupon campaign rules and lifecycle management.
alter table public.coupons add column if not exists discount_type text not null default 'fixed';
alter table public.coupons add column if not exists discount_value numeric(10, 2);
alter table public.coupons add column if not exists min_order_amount numeric(10, 2) not null default 0;
alter table public.coupons add column if not exists max_discount_amount numeric(10, 2);
alter table public.coupons add column if not exists valid_from timestamptz;
alter table public.coupons add column if not exists valid_until timestamptz;
alter table public.coupons add column if not exists validity_days integer;
alter table public.coupons add column if not exists total_issue_limit integer;
alter table public.coupons add column if not exists per_user_limit integer not null default 1;
alter table public.coupons add column if not exists applicable_order_types text[] not null default array['dinein', 'takeaway']::text[];
alter table public.coupons add column if not exists applicable_payment_methods text[] not null default array['cash', 'tng', 'stripe', 'wallet']::text[];
alter table public.coupons add column if not exists applicable_branch_ids text[] not null default array[]::text[];
alter table public.coupons add column if not exists exclude_delivery_fee boolean not null default true;
alter table public.coupons add column if not exists status text not null default 'active';
alter table public.coupons add column if not exists updated_at timestamptz not null default now();

update public.coupons
set discount_value = discount_amount
where discount_value is null;

alter table public.coupons alter column discount_value set not null;
alter table public.coupons drop constraint if exists coupons_discount_type_check;
alter table public.coupons add constraint coupons_discount_type_check check (discount_type in ('fixed', 'percentage'));
alter table public.coupons drop constraint if exists coupons_status_check;
alter table public.coupons add constraint coupons_status_check check (status in ('draft', 'active', 'paused', 'ended'));
alter table public.coupons drop constraint if exists coupons_discount_value_check;
alter table public.coupons add constraint coupons_discount_value_check check (
  discount_value >= 0
  and (discount_type <> 'percentage' or discount_value <= 100)
);
alter table public.coupons drop constraint if exists coupons_limits_check;
alter table public.coupons add constraint coupons_limits_check check (
  min_order_amount >= 0
  and (max_discount_amount is null or max_discount_amount > 0)
  and (validity_days is null or validity_days between 1 and 3650)
  and (total_issue_limit is null or total_issue_limit > 0)
  and per_user_limit between 1 and 100
  and (valid_until is null or valid_from is null or valid_until > valid_from)
);

alter table public.user_coupons add column if not exists issued_at timestamptz not null default now();
alter table public.user_coupons add column if not exists source text not null default 'admin';
alter table public.user_coupons add column if not exists issued_by_admin_id uuid references public.admin_users(id) on delete set null;
alter table public.user_coupons add column if not exists reserved_order_id uuid references public.orders(id) on delete set null;
alter table public.user_coupons add column if not exists reserved_at timestamptz;
alter table public.user_coupons add column if not exists reservation_expires_at timestamptz;
alter table public.user_coupons add column if not exists used_order_id uuid references public.orders(id) on delete set null;
alter table public.user_coupons add column if not exists revoked_at timestamptz;
alter table public.user_coupons add column if not exists revoked_by_admin_id uuid references public.admin_users(id) on delete set null;
alter table public.user_coupons add column if not exists revoke_reason text;
alter table public.user_coupons drop constraint if exists user_coupons_status_check;
alter table public.user_coupons add constraint user_coupons_status_check check (status in ('available', 'reserved', 'used', 'expired', 'revoked'));

alter table public.orders add column if not exists coupon_code text;
alter table public.orders add column if not exists coupon_title text;
alter table public.orders add column if not exists coupon_discount_type text;
alter table public.orders add column if not exists coupon_discount_value numeric(10, 2);
alter table public.orders add column if not exists coupon_rule_snapshot jsonb;
alter table public.orders add column if not exists coupon_status text;

create index if not exists coupons_status_validity_idx on public.coupons (status, valid_from, valid_until);
create index if not exists user_coupons_coupon_status_idx on public.user_coupons (coupon_id, status);
create index if not exists user_coupons_user_status_expiry_idx on public.user_coupons (user_id, status, expires_at);
create index if not exists user_coupons_reservation_expiry_idx on public.user_coupons (reservation_expires_at) where status = 'reserved';
create index if not exists user_coupons_used_order_idx on public.user_coupons (used_order_id) where used_order_id is not null;

drop trigger if exists coupons_set_updated_at on public.coupons;
create trigger coupons_set_updated_at
before update on public.coupons
for each row execute function public.set_updated_at();

alter table public.coupons enable row level security;
alter table public.user_coupons enable row level security;

revoke insert, update, delete on table public.coupons from anon, authenticated;
revoke insert, update, delete on table public.user_coupons from anon, authenticated;

create or replace function public.reserve_user_coupon(
  user_coupon_id_input uuid,
  user_id_input uuid,
  reservation_minutes_input integer default 30
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  changed_count integer;
begin
  update public.user_coupons
  set status = 'reserved',
      reserved_at = now(),
      reservation_expires_at = now() + make_interval(mins => greatest(1, least(reservation_minutes_input, 1440))),
      reserved_order_id = null
  where id = user_coupon_id_input
    and user_id = user_id_input
    and (
      status = 'available'
      or (status = 'reserved' and reservation_expires_at < now())
    )
    and (expires_at is null or expires_at > now());
  get diagnostics changed_count = row_count;
  return changed_count = 1;
end;
$$;

create or replace function public.release_user_coupon(
  user_coupon_id_input uuid,
  user_id_input uuid
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  changed_count integer;
begin
  update public.user_coupons
  set status = case when expires_at is not null and expires_at <= now() then 'expired' else 'available' end,
      reserved_at = null,
      reservation_expires_at = null,
      reserved_order_id = null,
      used_at = null,
      used_order_id = null
  where id = user_coupon_id_input
    and user_id = user_id_input
    and status in ('reserved', 'used');
  get diagnostics changed_count = row_count;
  return changed_count = 1;
end;
$$;

revoke execute on function public.reserve_user_coupon(uuid, uuid, integer) from public, anon, authenticated;
revoke execute on function public.release_user_coupon(uuid, uuid) from public, anon, authenticated;
grant execute on function public.reserve_user_coupon(uuid, uuid, integer) to service_role;
grant execute on function public.release_user_coupon(uuid, uuid) to service_role;
-- Agent / affiliate program -------------------------------------------------
-- All access is mediated by the Node API. These tables are intentionally not
-- exposed to anon/authenticated Data API roles.
create table if not exists public.agent_applications (
  id uuid primary key default gen_random_uuid(),
  application_no text not null unique,
  user_id uuid not null references public.users(id) on delete cascade,
  full_name text not null,
  region text not null,
  promotion_channel text not null,
  whatsapp_phone text not null,
  message text,
  status text not null default 'pending' check (status in ('pending', 'changes_requested', 'approved', 'rejected', 'activated')),
  consent_at timestamptz not null,
  reviewed_by uuid references public.admin_users(id) on delete set null,
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists agent_applications_open_user_idx
  on public.agent_applications (user_id)
  where status in ('pending', 'changes_requested', 'approved');
create index if not exists agent_applications_status_created_idx
  on public.agent_applications (status, created_at desc);
create index if not exists agent_applications_reviewed_by_idx
  on public.agent_applications (reviewed_by);

create table if not exists public.agents (
  id uuid primary key default gen_random_uuid(),
  agent_no text not null unique,
  user_id uuid not null unique references public.users(id) on delete restrict,
  referral_code text not null unique,
  full_name text,
  region text,
  promotion_channel text,
  whatsapp_phone text,
  status text not null default 'active' check (status in ('active', 'suspended', 'terminated')),
  commission_rate numeric(5, 2) check (commission_rate is null or (commission_rate >= 0 and commission_rate <= 100)),
  source text not null default 'application' check (source in ('application', 'admin_manual', 'admin_import')),
  application_id uuid unique references public.agent_applications(id) on delete set null,
  created_by_admin_id uuid references public.admin_users(id) on delete set null,
  activated_at timestamptz not null default now(),
  suspended_at timestamptz,
  suspension_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists agents_status_created_idx on public.agents (status, created_at desc);
create index if not exists agents_created_by_admin_idx on public.agents (created_by_admin_id);

-- Existing installations are upgraded in place. The current profile is copied
-- from the approved application so agents never receive a generated display name.
alter table public.agents add column if not exists full_name text;
alter table public.agents add column if not exists region text;
alter table public.agents add column if not exists promotion_channel text;
alter table public.agents add column if not exists whatsapp_phone text;
update public.agents a
set full_name = coalesce(nullif(a.full_name, ''), ap.full_name),
    region = coalesce(nullif(a.region, ''), ap.region),
    promotion_channel = coalesce(nullif(a.promotion_channel, ''), ap.promotion_channel),
    whatsapp_phone = coalesce(nullif(a.whatsapp_phone, ''), ap.whatsapp_phone)
from public.agent_applications ap
where a.application_id = ap.id
  and (a.full_name is null or a.region is null or a.promotion_channel is null or a.whatsapp_phone is null);

create table if not exists public.agent_profile_change_requests (
  id uuid primary key default gen_random_uuid(),
  request_no text not null unique,
  agent_id uuid not null references public.agents(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  before_data jsonb not null default '{}'::jsonb,
  requested_data jsonb not null default '{}'::jsonb,
  reason text,
  status text not null default 'pending' check (status in ('pending', 'changes_requested', 'approved', 'rejected', 'cancelled')),
  reviewed_by uuid references public.admin_users(id) on delete set null,
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists agent_profile_changes_one_open_idx
  on public.agent_profile_change_requests (agent_id)
  where status in ('pending', 'changes_requested');
create index if not exists agent_profile_changes_status_created_idx
  on public.agent_profile_change_requests (status, created_at desc);
create index if not exists agent_profile_changes_agent_created_idx
  on public.agent_profile_change_requests (agent_id, created_at desc);

create table if not exists public.agent_activation_codes (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.agent_applications(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  code_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  revoked_at timestamptz,
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  created_by uuid not null references public.admin_users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists agent_activation_codes_user_active_idx
  on public.agent_activation_codes (user_id, created_at desc)
  where used_at is null and revoked_at is null;
create index if not exists agent_activation_codes_application_idx
  on public.agent_activation_codes (application_id);
create index if not exists agent_activation_codes_created_by_idx
  on public.agent_activation_codes (created_by);

create table if not exists public.agent_commission_rules (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid references public.agents(id) on delete cascade,
  name text not null,
  commission_rate numeric(5, 2) not null check (commission_rate >= 0 and commission_rate <= 100),
  min_order_amount numeric(10, 2) not null default 0 check (min_order_amount >= 0),
  effective_from timestamptz not null default now(),
  effective_until timestamptz,
  active boolean not null default true,
  created_by uuid not null references public.admin_users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (effective_until is null or effective_until > effective_from)
);

create index if not exists agent_commission_rules_lookup_idx
  on public.agent_commission_rules (agent_id, active, effective_from desc);
create index if not exists agent_commission_rules_created_by_idx
  on public.agent_commission_rules (created_by);

create table if not exists public.agent_referrals (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.agents(id) on delete restrict,
  referred_user_id uuid not null unique references public.users(id) on delete restrict,
  referral_code text not null,
  attributed_at timestamptz not null default now(),
  attribution_expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists agent_referrals_agent_created_idx
  on public.agent_referrals (agent_id, created_at desc);

alter table public.orders add column if not exists agent_id uuid references public.agents(id) on delete set null;
alter table public.orders add column if not exists agent_referral_code text;
create index if not exists orders_agent_id_created_idx on public.orders (agent_id, created_at desc);

create table if not exists public.agent_order_attributions (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete restrict,
  agent_id uuid not null references public.agents(id) on delete restrict,
  referred_user_id uuid references public.users(id) on delete set null,
  referral_code text not null,
  eligible_amount numeric(10, 2) not null check (eligible_amount >= 0),
  commission_rate numeric(5, 2) not null check (commission_rate >= 0 and commission_rate <= 100),
  commission_amount numeric(10, 2) not null check (commission_amount >= 0),
  rule_snapshot jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'available', 'voided', 'paid')),
  available_at timestamptz,
  voided_at timestamptz,
  void_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists agent_order_attributions_agent_status_idx
  on public.agent_order_attributions (agent_id, status, created_at desc);
create index if not exists agent_order_attributions_referred_user_idx
  on public.agent_order_attributions (referred_user_id);

create table if not exists public.agent_commission_ledger (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.agents(id) on delete restrict,
  order_id uuid references public.orders(id) on delete restrict,
  attribution_id uuid references public.agent_order_attributions(id) on delete restrict,
  entry_type text not null check (entry_type in ('commission', 'adjustment', 'reversal', 'payout')),
  amount numeric(10, 2) not null check (amount <> 0),
  status text not null default 'pending' check (status in ('pending', 'available', 'paid', 'voided')),
  note text,
  created_by uuid references public.admin_users(id) on delete set null,
  available_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists agent_commission_ledger_order_commission_idx
  on public.agent_commission_ledger (order_id)
  where entry_type = 'commission';
create index if not exists agent_commission_ledger_agent_status_idx
  on public.agent_commission_ledger (agent_id, status, created_at desc);
create index if not exists agent_commission_ledger_attribution_idx
  on public.agent_commission_ledger (attribution_id);
create index if not exists agent_commission_ledger_created_by_idx
  on public.agent_commission_ledger (created_by);

create table if not exists public.agent_payouts (
  id uuid primary key default gen_random_uuid(),
  payout_no text not null unique,
  agent_id uuid not null references public.agents(id) on delete restrict,
  amount numeric(10, 2) not null check (amount > 0),
  payment_method text not null default 'bank',
  payment_details jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'approved', 'paid', 'rejected')),
  requested_at timestamptz not null default now(),
  reviewed_by uuid references public.admin_users(id) on delete set null,
  reviewed_at timestamptz,
  paid_at timestamptz,
  review_note text,
  created_at timestamptz not null default now()
);

create index if not exists agent_payouts_agent_status_idx
  on public.agent_payouts (agent_id, status, created_at desc);
create index if not exists agent_payouts_reviewed_by_idx on public.agent_payouts (reviewed_by);
create unique index if not exists agent_payouts_one_open_per_agent_idx
  on public.agent_payouts (agent_id)
  where status in ('pending', 'approved');

alter table public.agent_commission_ledger add column if not exists payout_id uuid references public.agent_payouts(id) on delete restrict;
drop index if exists public.agent_commission_ledger_payout_unique_idx;
create unique index agent_commission_ledger_payout_unique_idx
  on public.agent_commission_ledger (payout_id);

create table if not exists public.agent_audit_logs (
  id uuid primary key default gen_random_uuid(),
  admin_user_id uuid references public.admin_users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  before_data jsonb,
  after_data jsonb,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists agent_audit_logs_entity_idx
  on public.agent_audit_logs (entity_type, entity_id, created_at desc);
create index if not exists agent_audit_logs_admin_idx
  on public.agent_audit_logs (admin_user_id, created_at desc);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'agent_applications', 'agents', 'agent_activation_codes',
    'agent_commission_rules', 'agent_referrals', 'agent_order_attributions',
    'agent_commission_ledger', 'agent_payouts', 'agent_audit_logs',
    'agent_profile_change_requests'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
    execute format('grant select, insert, update, delete on table public.%I to service_role', table_name);
  end loop;
end $$;

drop trigger if exists set_agent_applications_updated_at on public.agent_applications;
create trigger set_agent_applications_updated_at before update on public.agent_applications
for each row execute function public.set_updated_at();
drop trigger if exists set_agents_updated_at on public.agents;
create trigger set_agents_updated_at before update on public.agents
for each row execute function public.set_updated_at();
drop trigger if exists set_agent_profile_changes_updated_at on public.agent_profile_change_requests;
create trigger set_agent_profile_changes_updated_at before update on public.agent_profile_change_requests
for each row execute function public.set_updated_at();
drop trigger if exists set_agent_commission_rules_updated_at on public.agent_commission_rules;
create trigger set_agent_commission_rules_updated_at before update on public.agent_commission_rules
for each row execute function public.set_updated_at();
drop trigger if exists set_agent_order_attributions_updated_at on public.agent_order_attributions;
create trigger set_agent_order_attributions_updated_at before update on public.agent_order_attributions
for each row execute function public.set_updated_at();

drop function if exists public.activate_agent_with_code(uuid, text, text, text);
create function public.activate_agent_with_code(
  user_id_input uuid,
  code_hash_input text,
  agent_no_input text,
  referral_code_input text
)
returns text
language plpgsql
security invoker
set search_path = public
as $$
declare
  activation public.agent_activation_codes%rowtype;
  new_agent_id uuid;
begin
  select * into activation
  from public.agent_activation_codes
  where user_id = user_id_input
    and used_at is null
    and revoked_at is null
    and expires_at > now()
  order by created_at desc
  limit 1
  for update;

  if activation.id is null then return 'UNAVAILABLE'; end if;
  if activation.failed_attempts >= 5 then return 'LOCKED'; end if;
  if activation.code_hash <> code_hash_input then
    update public.agent_activation_codes set failed_attempts = failed_attempts + 1 where id = activation.id;
    return 'INVALID';
  end if;

  insert into public.agents (
    agent_no, user_id, referral_code, full_name, region, promotion_channel,
    whatsapp_phone, source, application_id, created_by_admin_id
  )
  select
    agent_no_input, user_id_input, referral_code_input, application.full_name,
    application.region, application.promotion_channel, application.whatsapp_phone,
    'application', activation.application_id, activation.created_by
  from public.agent_applications application
  where application.id = activation.application_id
  returning id into new_agent_id;

  update public.agent_activation_codes set used_at = now() where id = activation.id;
  update public.agent_applications set status = 'activated', updated_at = now()
    where id = activation.application_id and user_id = user_id_input;
  return new_agent_id::text;
end;
$$;

revoke all on function public.activate_agent_with_code(uuid, text, text, text) from public, anon, authenticated;
grant execute on function public.activate_agent_with_code(uuid, text, text, text) to service_role;

-- Deletes only an agent that has no financial or order-attribution history.
-- The function runs as one transaction and intentionally keeps the ordinary user
-- account plus audit history. It is callable only by the server service role.
create or replace function public.delete_agent_if_safe(
  agent_id_input uuid,
  admin_id_input uuid
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  target_agent public.agents%rowtype;
  target_application_id uuid;
  removed_referrals integer := 0;
begin
  select * into target_agent
  from public.agents
  where id = agent_id_input
  for update;

  if not found then
    raise exception '未找到代理记录';
  end if;

  if exists (select 1 from public.agent_order_attributions where agent_id = target_agent.id) then
    raise exception '该代理已有订单归因记录，不能删除，请改为暂停或终止';
  end if;
  if exists (select 1 from public.agent_commission_ledger where agent_id = target_agent.id) then
    raise exception '该代理已有佣金流水，不能删除，请改为暂停或终止';
  end if;
  if exists (select 1 from public.agent_payouts where agent_id = target_agent.id) then
    raise exception '该代理已有提现记录，不能删除，请改为暂停或终止';
  end if;

  delete from public.agent_referrals where agent_id = target_agent.id;
  get diagnostics removed_referrals = row_count;

  target_application_id := target_agent.application_id;
  if target_application_id is not null then
    delete from public.agent_activation_codes where application_id = target_application_id;
    delete from public.agent_applications where id = target_application_id;
  end if;

  delete from public.agents where id = target_agent.id;

  insert into public.agent_audit_logs (
    admin_user_id, action, entity_type, entity_id, before_data, after_data, note
  ) values (
    admin_id_input,
    'delete_agent',
    'agent',
    target_agent.id,
    jsonb_build_object(
      'agentNo', target_agent.agent_no,
      'userId', target_agent.user_id,
      'referralCode', target_agent.referral_code,
      'source', target_agent.source
    ),
    jsonb_build_object('removedReferrals', removed_referrals),
    '仅无订单归因、佣金流水和提现记录的代理允许删除'
  );

  return jsonb_build_object(
    'agentNo', target_agent.agent_no,
    'removedReferrals', removed_referrals
  );
end;
$$;

revoke all on function public.delete_agent_if_safe(uuid, uuid) from public, anon, authenticated;
grant execute on function public.delete_agent_if_safe(uuid, uuid) to service_role;

-- Delivery pricing, quote locks, and manually approved out-of-range requests.
create table if not exists public.delivery_settings (
  id text primary key default 'default',
  max_auto_distance_km numeric(6, 2) not null default 20,
  lalamove_enabled boolean not null default false,
  lalamove_markup_percent numeric(6, 2) not null default 15,
  quote_lock_minutes integer not null default 30,
  request_expiry_minutes integer not null default 120,
  approval_expiry_minutes integer not null default 30,
  fallback_fee_tiers jsonb not null default '[{"maxKm":3,"fee":6},{"maxKm":5,"fee":8},{"maxKm":8,"fee":12},{"maxKm":10,"fee":15},{"maxKm":12,"fee":18},{"maxKm":15,"fee":22},{"maxKm":18,"fee":26},{"maxKm":20,"fee":30}]'::jsonb,
  updated_by uuid references public.admin_users(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint delivery_settings_singleton check (id = 'default'),
  constraint delivery_settings_values_check check (
    max_auto_distance_km > 0 and max_auto_distance_km <= 100
    and lalamove_markup_percent >= 0 and lalamove_markup_percent <= 200
    and quote_lock_minutes between 5 and 180
    and request_expiry_minutes between 15 and 1440
    and approval_expiry_minutes between 5 and 240
    and jsonb_typeof(fallback_fee_tiers) = 'array'
  )
);

insert into public.delivery_settings (id) values ('default') on conflict (id) do nothing;

create table if not exists public.delivery_quotes (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  user_id uuid references public.users(id) on delete set null,
  actor_hash text not null,
  branch_id text not null references public.store_branches(id),
  branch_name text not null,
  address text not null,
  address_hash text not null,
  latitude numeric(10, 7) not null,
  longitude numeric(10, 7) not null,
  distance_km numeric(10, 2) not null,
  duration_min integer not null,
  deliverability text not null default 'deliverable',
  source text not null,
  provider_quote_id text,
  provider_cost numeric(10, 2),
  customer_fee numeric(10, 2) not null,
  fallback_reason text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint delivery_quotes_source_check check (source in ('lalamove', 'fallback')),
  constraint delivery_quotes_deliverability_check check (deliverability in ('deliverable', 'manual_confirmation_required')),
  constraint delivery_quotes_values_check check (
    distance_km > 0 and duration_min > 0 and customer_fee >= 0
    and (provider_cost is null or provider_cost >= 0)
  )
);

alter table public.delivery_quotes add column if not exists deliverability text not null default 'deliverable';
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'delivery_quotes_deliverability_check'
      and conrelid = 'public.delivery_quotes'::regclass
  ) then
    alter table public.delivery_quotes
      add constraint delivery_quotes_deliverability_check
      check (deliverability in ('deliverable', 'manual_confirmation_required'));
  end if;
end;
$$;

create index if not exists delivery_quotes_actor_created_idx on public.delivery_quotes (actor_hash, created_at desc);
create index if not exists delivery_quotes_cache_idx on public.delivery_quotes (branch_id, latitude, longitude, source, created_at desc);
create index if not exists delivery_quotes_expires_idx on public.delivery_quotes (expires_at);

create table if not exists public.delivery_approval_requests (
  id uuid primary key default gen_random_uuid(),
  request_no text not null unique,
  user_id uuid not null references public.users(id) on delete cascade,
  status text not null default 'pending',
  branch_id text not null references public.store_branches(id),
  branch_name text not null,
  customer_name text not null,
  customer_phone text not null,
  address text not null,
  address_hash text not null,
  latitude numeric(10, 7) not null,
  longitude numeric(10, 7) not null,
  distance_km numeric(10, 2) not null,
  duration_min integer not null,
  cart_hash text not null,
  cart_snapshot jsonb not null,
  subtotal numeric(10, 2) not null,
  approved_delivery_fee numeric(10, 2),
  delivery_provider text,
  estimated_delivery_min integer,
  customer_note text,
  review_note text,
  reviewed_by uuid references public.admin_users(id) on delete set null,
  reviewed_by_name text,
  reviewed_at timestamptz,
  request_expires_at timestamptz not null,
  approval_expires_at timestamptz,
  consumed_order_id uuid references public.orders(id) on delete set null,
  consumed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint delivery_approval_status_check check (status in ('pending', 'approved', 'rejected', 'cancelled', 'expired', 'consumed')),
  constraint delivery_approval_values_check check (
    distance_km > 0 and duration_min > 0 and subtotal >= 0
    and (approved_delivery_fee is null or approved_delivery_fee >= 0)
    and (estimated_delivery_min is null or estimated_delivery_min > 0)
  )
);

create unique index if not exists delivery_approval_one_active_user_idx
  on public.delivery_approval_requests (user_id) where status in ('pending', 'approved');
create index if not exists delivery_approval_user_created_idx on public.delivery_approval_requests (user_id, created_at desc);
create index if not exists delivery_approval_status_created_idx on public.delivery_approval_requests (status, created_at desc);

alter table public.orders add column if not exists delivery_quote_id uuid references public.delivery_quotes(id) on delete set null;
alter table public.orders add column if not exists delivery_approval_request_id uuid references public.delivery_approval_requests(id) on delete set null;
create unique index if not exists orders_delivery_approval_unique_idx
  on public.orders (delivery_approval_request_id) where delivery_approval_request_id is not null;
create index if not exists orders_delivery_quote_idx on public.orders (delivery_quote_id);

alter table public.delivery_settings enable row level security;
alter table public.delivery_quotes enable row level security;
alter table public.delivery_approval_requests enable row level security;
revoke all on table public.delivery_settings, public.delivery_quotes, public.delivery_approval_requests from public, anon, authenticated;
grant select, insert, update, delete on table public.delivery_settings, public.delivery_quotes, public.delivery_approval_requests to service_role;

drop trigger if exists delivery_settings_set_updated_at on public.delivery_settings;
create trigger delivery_settings_set_updated_at before update on public.delivery_settings
for each row execute function public.set_updated_at();
drop trigger if exists delivery_approval_requests_set_updated_at on public.delivery_approval_requests;
create trigger delivery_approval_requests_set_updated_at before update on public.delivery_approval_requests
for each row execute function public.set_updated_at();
