export const additionalAdminEnglishText: Record<string, string> = {
  '保存更改': 'Save changes',
  '报价来源': 'Quote source',
  '本页累计消费': 'Page total spending',
  '本页钱包余额': 'Page wallet balance',
  '本页用户': 'Users on this page',
  '必选': 'Required',
  '编辑菜品': 'Edit menu item',
  '编辑分类': 'Edit category',
  '编辑后台账号': 'Edit admin account',
  '编辑门店': 'Edit store',
  '编辑账号': 'Edit account',
  '补充这笔收支的说明': 'Add details about this transaction',
  '补充资料': 'Request more information',
  '财务数据加载失败': 'Failed to load financial data',
  '菜品编码已存在，请更换编码': 'This menu item code already exists. Please use another code.',
  '菜品不存在，请刷新菜单后重试': 'This menu item no longer exists. Refresh the menu and try again.',
  '菜品名称已存在，请更换名称': 'This menu item name already exists. Please use another name.',
  '菜品明细': 'Menu item details',
  '菜品属性标签': 'Menu item attribute tags',
  '菜品图片': 'Menu item image',
  '菜品已更新': 'Menu item updated',
  '菜品已下架': 'Menu item deactivated',
  '菜品已新增': 'Menu item added',
  '操作失败': 'Action failed',
  '查重失败': 'Duplicate check failed',
  '充值失败': 'Top-up failed',
  '初始密码': 'Initial password',
  '厨房工人': 'Kitchen staff',
  '处理​​中': 'Processing',
  '创建订单': 'Create order',
  '创建分类': 'Create category',
  '创建门店': 'Create store',
  '创建账号': 'Create account',
  '从未登录': 'Never signed in',
  '代客下单': 'Create order for customer',
  '代客下单失败': 'Failed to create customer order',
  '代理管理': 'Agent management',
  '代理申请已通过': 'Agent application approved',
  '代理数据加载失败': 'Failed to load agent data',
  '代理通知文案已复制': 'Agent notification copied',
  '代理已删除': 'Agent deleted',
  '代理状态已更新': 'Agent status updated',
  '带动销售额': 'Attributed sales',
  '待安排': 'Unassigned',
  '待处理': 'Pending',
  '待处理提现': 'Pending withdrawals',
  '待付款': 'Awaiting payment',
  '待计算': 'Not calculated',
  '待取餐': 'Awaiting pickup',
  '待审核': 'Pending review',
  '待审核申请': 'Applications pending review',
  '待自动解析': 'Pending automatic lookup',
  '到店/现金支付': 'Pay in store / cash',
  '地址填写完成后，请计算配送距离和费用': 'After entering the address, calculate the delivery distance and fee.',
  '登录': 'Sign in',
  '登录成功': 'Signed in successfully',
  '登录失败': 'Sign-in failed',
  '登录账号': 'Login account',
  '等待取餐': 'Waiting for pickup',
  '第三方配送单号': 'Third-party delivery number',
  '店内配送': 'In-house delivery',
  '店员或骑手姓名': 'Staff member or rider name',
  '店长': 'Store manager',
  '订单备注': 'Order note',
  '订单记录': 'Order history',
  '订单类型': 'Order type',
  '订单退款': 'Order refund',
  '订单状态更新失败': 'Failed to update order status',
  '读取图片失败': 'Failed to read image',
  '额外收入已记录': 'Additional income recorded',
  '发放原因': 'Issue reason',
  '返回': 'Back',
  '分类保存失败': 'Failed to save category',
  '分类加载失败': 'Failed to load categories',
  '分类名称': 'Category name',
  '分类删除失败': 'Failed to delete category',
  '分类已更新': 'Category updated',
  '分类已启用': 'Category enabled',
  '分类已删除': 'Category deleted',
  '分类已停用': 'Category disabled',
  '分类已新增': 'Category added',
  '分类状态更新失败': 'Failed to update category status',
  '分配门店': 'Assign store',
  '服务费': 'Service charge',
  '付款截图必须是 JPG 或 PNG 图片': 'Payment proof must be a JPG or PNG image.',
  '付款截图不能超过 5MB': 'Payment proof cannot exceed 5 MB.',
  '付款截图读取失败': 'Failed to read payment proof',
  '付款截图已拒绝，订单恢复现金待支付': 'Payment proof rejected. The order has returned to cash payment pending.',
  '付款截图已审核通过': 'Payment proof approved',
  '付款审核拒绝': 'Payment review rejected',
  '付款审核失败': 'Payment review failed',
  '付款审核通过': 'Payment review approved',
  '更新中': 'Updating',
  '供应商 / 商家': 'Supplier / merchant',
  '顾客创建失败': 'Failed to create customer',
  '顾客姓名': 'Customer name',
  '顾客已创建': 'Customer created',
  '管理员': 'Administrator',
  '管理员账号已创建': 'Administrator account created',
  '规格组译名': 'Option group translation',
  '规则名称': 'Rule name',
  '核对全部信息后创建订单': 'Review all information before creating the order',
  '后台': 'Admin',
  '后台创建': 'Created by admin',
  '后台代下单': 'Admin-created order',
  '会员钱包': 'Member wallet',
  '活动截止时间': 'Campaign end time',
  '活动已结束': 'Campaign ended',
  '活动已上线': 'Campaign published',
  '活动已暂停': 'Campaign paused',
  '活动赠送': 'Campaign reward',
  '活动状态更新失败': 'Failed to update campaign status',
  '基本资料': 'Profile details',
  '计算配送费': 'Calculate delivery fee',
  '计算中...': 'Calculating...',
  '记录额外收入': 'Record additional income',
  '记录一笔开支': 'Record an expense',
  '加价': 'Price adjustment',
  '拒绝时填写原因': 'Enter a reason when rejecting',
  '经营分析': 'Business analytics',
  '经营结余': 'Operating balance',
  '经度': 'Longitude',
  '距离': 'Distance',
  '开支': 'Expenses',
  '开支已记录': 'Expense recorded',
  '可留空自动解析': 'Leave blank for automatic lookup',
  '可使用': 'Available',
  '可选': 'Optional',
  '可一键拨打': 'Tap to call',
  '客服助理': 'Customer service',
  '老板': 'Owner',
  '历史规则': 'Rule history',
  '立即': 'Immediately',
  '领取后有效天数': 'Valid days after claim',
  '浏览器不支持图片转换': 'This browser does not support image conversion.',
  '留空则使用中文名称': 'Leave blank to use the Chinese name',
  '门店 ID': 'Store ID',
  '门店保存失败': 'Failed to save store',
  '门店地址': 'Store address',
  '门店名称': 'Store name',
  '门店已更新': 'Store updated',
  '门店已启用': 'Store enabled',
  '门店已停用': 'Store disabled',
  '门店已新增': 'Store added',
  '门店营业中': 'Store open',
  '门店员工': 'Store staff',
  '门店状态更新失败': 'Failed to update store status',
  '门店总数': 'Total stores',
  '门牌、交接或收款说明': 'Unit, handoff, or payment instructions',
  '默认': 'Default',
  '默认代理佣金': 'Default agent commission',
  '默认规则': 'Default rule',
  '排序更新失败': 'Failed to update sort order',
  '排序已更新': 'Sort order updated',
  '配送安排保存失败': 'Failed to save delivery assignment',
  '配送备注': 'Delivery note',
  '配送超时': 'Delivery overdue',
  '配送订单加载失败': 'Failed to load delivery orders',
  '配送方式': 'Delivery method',
  '配送费计算失败': 'Failed to calculate delivery fee',
  '配送人员': 'Delivery staff',
  '配送信息': 'Delivery information',
  '配送员电话': 'Rider phone',
  '配送员姓名': 'Rider name',
  '配送状态更新失败': 'Failed to update delivery status',
  '批量代理注册已执行': 'Bulk agent registration completed',
  '平均客单': 'Average order value',
  '其他': 'Other',
  '其他配送': 'Other delivery',
  '启用分类': 'Enable category',
  '钱包流水': 'Wallet transactions',
  '钱包消费': 'Wallet spending',
  '请上传顾客付款截图': 'Upload the customer payment proof.',
  '请输入冲销原因': 'Enter a reversal reason',
  '请输入管理员账号': 'Enter administrator account',
  '请输入管理员账号和密码，进入门店运营控制台。': 'Enter your administrator account and password to access store operations.',
  '请输入拒绝原因': 'Enter a rejection reason',
  '请输入密码': 'Enter password',
  '请输入需要补充的资料': 'Enter the additional information required',
  '请输入用户姓名': 'Enter user name',
  '请输入暂停原因': 'Enter a reason for pausing',
  '请添加菜品': 'Add at least one menu item.',
  '请填写拒绝原因': 'Enter a rejection reason.',
  '请填写门店 ID': 'Enter the store ID.',
  '请填写修改原因': 'Enter the reason for this change.',
  '请先填写菜品编码，图片会按 {item_code}.{webp|jpg} 命名': 'Enter the menu item code first. The image will be named {item_code}.{webp|jpg}.',
  '请选择顾客': 'Select a customer.',
  '请选择图片文件': 'Select an image file.',
  '请选择优惠券和用户': 'Select a coupon and at least one user.',
  '请选择有效门店': 'Select an active store.',
  '取餐超时': 'Pickup overdue',
  '券码': 'Coupon code',
  '确认充值': 'Confirm top-up',
  '确认创建': 'Confirm creation',
  '确认订单': 'Confirm order',
  '删除分类': 'Delete category',
  '删除规格组': 'Delete option group',
  '删除选项': 'Delete option',
  '删除账号': 'Delete account',
  '设置订单类型、门店和就餐信息': 'Set the order type, store, and dining information',
  '申请审核': 'Application review',
  '申请已拒绝': 'Application rejected',
  '审核备注（可留空）': 'Review note (optional)',
  '审核状态': 'Review status',
  '生日': 'Birthday',
  '生效中': 'Active',
  '实际配送成本（RM）': 'Actual delivery cost (RM)',
  '收据号、银行流水号等': 'Receipt number, bank reference, etc.',
  '收入来源': 'Income source',
  '收支明细': 'Income and expense details',
  '手机号': 'Phone number',
  '手机号或姓名': 'Phone number or name',
  '输入 setup token，创建第一个拥有后台权限的管理员账号。': 'Enter the setup token to create the first administrator account.',
  '输入菜品属性后回车': 'Enter an attribute and press Enter',
  '输入调整金额，可使用负数冲正': 'Enter an adjustment amount; use a negative value to reverse',
  '输入调整原因': 'Enter adjustment reason',
  '输入手机号或顾客姓名': 'Enter phone number or customer name',
  '输入完整配送地址': 'Enter the full delivery address',
  '输入姓名或手机号': 'Enter name or phone number',
  '输入译文属性后回车': 'Enter a translated attribute and press Enter',
  '刷新财务数据': 'Refresh financial data',
  '刷新菜单': 'Refresh menu',
  '搜索并选择本次下单的顾客': 'Search for and select the customer for this order',
  '搜索菜品名称或编码': 'Search menu item name or code',
  '搜索分类、供应商或备注': 'Search category, supplier, or note',
  '搜索分类名称': 'Search category name',
  '搜索顾客': 'Search customers',
  '搜索活动名称或券码': 'Search campaign name or coupon code',
  '搜索门店名称或地址': 'Search store name or address',
  '搜索姓名、手机号、代理编号、推广码': 'Search name, phone, agent ID, or referral code',
  '搜索姓名、手机号或邮箱': 'Search name, phone, or email',
  '搜索用户': 'Search users',
  '搜索账号或显示名称': 'Search account or display name',
  '所属门店': 'Assigned store',
  '锁定中': 'Locked',
  '泰文': 'Thai',
  '提交修改': 'Submit change',
  '提交中': 'Submitting',
  '提交中...': 'Submitting...',
  '提现审核': 'Withdrawal review',
  '提现已标记付款': 'Withdrawal marked as paid',
  '提现已拒绝': 'Withdrawal rejected',
  '提现已批准': 'Withdrawal approved',
  '添加菜品': 'Add menu item',
  '添加菜品备注': 'Add menu item note',
  '停用分类': 'Disable category',
  '通知状态': 'Notification status',
  '图片处理失败': 'Failed to process image',
  '外卖配送': 'Delivery',
  '网站下单': 'Website order',
  '纬度': 'Latitude',
  '未命名顾客': 'Unnamed customer',
  '未设置显示名称': 'Display name not set',
  '未填写': 'Not provided',
  '未填写地址': 'Address not provided',
  '未选择': 'Not selected',
  '无备注': 'No note',
  '无菜品资料': 'No menu item data',
  '无需审核': 'No review required',
  '详情': 'Details',
  '详细地址': 'Full address',
  '新密码（留空则不修改）': 'New password (leave blank to keep current)',
  '选择 JPG 或 PNG 图片': 'Select a JPG or PNG image',
  '选择并处理图片': 'Select and process image',
  '选择菜品': 'Select menu items',
  '选择菜品并调整订单数量': 'Select menu items and adjust quantities',
  '选择方式': 'Select method',
  '选择顾客': 'Select customer',
  '选择门店': 'Select store',
  '选择优惠券': 'Select coupon',
  '移除菜品': 'Remove menu item',
  '已撤销': 'Reversed',
  '已出餐': 'Ready for pickup',
  '已付款': 'Paid',
  '已过期': 'Expired',
  '已核销且未取消订单': 'Redeemed, non-cancelled orders',
  '已激活': 'Activated',
  '已经在当前分类边界': 'Already at the edge of this category',
  '已拒绝': 'Rejected',
  '已上传': 'Uploaded',
  '已使用': 'Used',
  '已锁定': 'Locked',
  '已通过': 'Approved',
  '已要求补充资料': 'Additional information requested',
  '已支付': 'Paid',
  '已终止': 'Terminated',
  '银行卡': 'Bank card',
  '银行转账': 'Bank transfer',
  '应付': 'Amount due',
  '营销活动发放': 'Marketing campaign issue',
  '营业中': 'Open',
  '佣金 %': 'Commission %',
  '佣金规则已保存': 'Commission rule saved',
  '佣金设置': 'Commission settings',
  '佣金已调整': 'Commission adjusted',
  '用餐信息': 'Dining information',
  '用户查询失败': 'Failed to search users',
  '用户创建失败': 'Failed to create user',
  '用户详情': 'User details',
  '用户详情加载失败': 'Failed to load user details',
  '用户姓名': 'User name',
  '用户已创建，钱包已自动开通': 'User created and wallet opened automatically',
  '用户资料': 'User profile',
  '用于衡量优惠带来的订单质量': 'Measures the quality of orders generated by promotions',
  '优惠成本': 'Discount cost',
  '优惠订单客单价': 'Average promoted order value',
  '优惠订单实际应付金额': 'Actual amount paid on discounted orders',
  '优惠券': 'Coupon',
  '优惠券保存失败': 'Failed to save coupon',
  '优惠券草稿已保存': 'Coupon draft saved',
  '优惠券发放失败': 'Failed to issue coupons',
  '优惠券数据加载失败': 'Failed to load coupon data',
  '优惠券已创建并上线': 'Coupon created and published',
  '邮箱': 'Email',
  '有效代理': 'Active agents',
  '有效订单': 'Valid orders',
  '余额补偿': 'Balance adjustment',
  '预计取餐': 'Estimated pickup',
  '预计时间': 'Estimated time',
  '预计送达': 'Estimated delivery',
  '原图不能超过 5MB': 'The original image cannot exceed 5 MB.',
  '越南语': 'Vietnamese',
  '暂无代理申请': 'No agent applications',
  '暂无订单记录': 'No order records',
  '暂无配送地址': 'No delivery address',
  '暂无钱包流水': 'No wallet transactions',
  '暂无提现申请': 'No withdrawal requests',
  '暂无佣金规则，订单暂不产生佣金': 'No commission rules. Orders will not generate commission yet.',
  '暂无优惠券': 'No coupons',
  '账号保存失败': 'Failed to save account',
  '账号角色': 'Account role',
  '账号删除失败': 'Failed to delete account',
  '账号已创建': 'Account created',
  '账号已更新': 'Account updated',
  '账号已启用': 'Account enabled',
  '账号已删除': 'Account deleted',
  '账号已停用': 'Account disabled',
  '账目已冲销': 'Transaction reversed',
  '账目已审核': 'Transaction reviewed',
  '折扣百分比': 'Discount percentage',
  '正常': 'Normal',
  '正在入账': 'Posting',
  '正在同步配送订单': 'Syncing delivery orders',
  '支付方式修改': 'Payment method change',
  '支付方式修改失败': 'Failed to change payment method',
  '支付方式已更正，等待管理员审核': 'Payment method corrected and awaiting administrator review',
  '支付与金额': 'Payment & amount',
  '指定代理': 'Assigned agent',
  '至少 8 位': 'At least 8 characters',
  '中文名称': 'Chinese name',
  '注册来源': 'Registration source',
  '状态更新失败': 'Failed to update status',
  '准备中': 'Preparing',
  '自主注册': 'Self registration',
  '自助注册': 'Self registration',
  '组 ID': 'Group ID',
  '组名称': 'Group name',
  '最低订单': 'Minimum order',
  '最后登录': 'Last sign-in',
  'Grab / Lalamove 单号（可选）': 'Grab / Lalamove number (optional)',
  'PUDU 区': 'PUDU area',
  '· 最低订单 RM': '· Minimum order RM',
  '（选填）': '(optional)',
  '+ 额外收入': '+ Additional income',
  '+ 记录开支': '+ Record expense',
  '0123456789,张三,5': '0123456789,John Doe,5',
  '60123456789,李四': '60123456789,Jane Doe',
  '0123456789,张三,5\n60123456789,李四': '0123456789,John Doe,5\n60123456789,Jane Doe',
  '安排配送': 'Arrange delivery',
  '按分类统计已记录开支': 'Recorded expenses by category',
  '保存并立即生效': 'Save and apply now',
  '保存配送安排': 'Save delivery assignment',
  '保存失败': 'Save failed',
  '备注：': 'Note:',
  '笔待审核': 'pending review',
  '采购、包装、水电或其他支出': 'Purchases, packaging, utilities, or other expenses',
  '菜单 CRUD、订单状态和管理员账号登录已完成，这个模块的列表与操作入口已预留。': 'This module is reserved for top-up review records and actions.',
  '查看本次付款截图': 'View this payment proof',
  '查看付款截图': 'View payment proof',
  '查看详情': 'View details',
  '查询用户': 'Search users',
  '充值': 'Top up',
  '充值后余额': 'Balance after top-up',
  '充值金额（RM）': 'Top-up amount (RM)',
  '充值来源': 'Top-up source',
  '充值原因': 'Top-up reason',
  '冲销': 'Reverse',
  '创建并选择': 'Create and select',
  '创建后系统会自动开通余额为 RM 0.00 的钱包。': 'A wallet with an RM 0.00 balance will be opened automatically after creation.',
  '代理': 'Agent',
  '单价': 'Unit price',
  '单选': 'Single choice',
  '当前菜品没有规格或加料': 'This menu item has no options or add-ons.',
  '当前范围还没有收支记录': 'No income or expense records in this range.',
  '当前付款状态不可修改': 'The current payment status cannot be changed.',
  '当前没有': 'No current ',
  '当前显示': 'Currently showing',
  '当前余额': 'Current balance',
  '地址': 'Address',
  '等待上传图片': 'Waiting to upload image',
  '第': 'Page ',
  '店内配送员': 'In-house rider',
  '调账': 'Adjust balance',
  '订单号': 'Order number',
  '订单收入自动汇总，手工账目单独标记': 'Order revenue is summarized automatically; manual entries are marked separately.',
  '订单无需重复记账。': 'Orders do not need to be recorded again.',
  '订单摘要': 'Order summary',
  '多选': 'Multiple choice',
  '多语言翻译': 'Translations',
  '发放 / 核销': 'Issued / redeemed',
  '发放时间': 'Issue time',
  '发送给申请人的通知文案': 'Message to send to the applicant',
  '分类顺序由排序数字决定': 'Category order is determined by the sort number.',
  '付款参考编号（选填）': 'Payment reference (optional)',
  '付款截图': 'Payment proof',
  '复制通知文案': 'Copy notification',
  '高权限': 'Elevated access',
  '个分类': 'categories',
  '个账号': 'accounts',
  '给': 'to',
  '更换顾客': 'Change customer',
  '关闭配送安排': 'Close delivery assignment',
  '关联菜品': 'Related menu items',
  '管理门店资料、营业状态与配送位置': 'Manage store details, operating status, and delivery location.',
  '规格 / 加料': 'Options / add-ons',
  '规格 / 加料翻译': 'Option / add-on translations',
  '规格组': 'Option group',
  '核销/过期': 'Redeemed / expired',
  '活动': 'Campaign',
  '记开支': 'Record expense',
  '记收入': 'Record income',
  '加入': 'Add',
  '简介': 'Description',
  '件商品': 'items',
  '角色': 'Role',
  '今日流水': 'Today’s transactions',
  '仅老板或管理员可批量注册代理。': 'Only owners or administrators can register agents in bulk.',
  '仅限授权管理员访问，所有操作将记录在系统日志中。': 'Authorized administrators only. All actions are recorded in the system log.',
  '近 30 天收支趋势': '30-day income and expense trend',
  '拒绝': 'Reject',
  '开支构成': 'Expense breakdown',
  '可以使用。': 'is available.',
  '累计消费': 'Lifetime spending',
  '例如 厨房早班': 'e.g. Kitchen morning shift',
  '例如 炖汤': 'e.g. Soup',
  '例如 份量 / 加料': 'e.g. Size / add-ons',
  '例如 加大': 'e.g. Large',
  '例如 A1': 'e.g. A1',
  '例如 bukit-bintang': 'e.g. bukit-bintang',
  '例如 large': 'e.g. large',
  '例如 portion': 'e.g. portion',
  '例如 S19': 'e.g. S19',
  '例如 service01': 'e.g. service01',
  '例如 Soup / Drinks': 'e.g. Soup / Drinks',
  '例如：012-345 6789': 'e.g. 012-345 6789',
  '例如：公司团餐': 'e.g. Corporate catering',
  '例如：顾客实际使用转账付款': 'e.g. Customer paid by bank transfer',
  '例如：门店收到现金，后台代充值': 'e.g. Store received cash and applied a manual top-up',
  '例如：早市蔬菜档': 'e.g. Market vegetable supplier',
  '绿色为收入，红色为开支': 'Green is income; red is expense.',
  '马来西亚手机号': 'Malaysian phone number',
  '没有符合条件的菜品': 'No matching menu items',
  '没有符合条件的分类': 'No matching categories',
  '没有符合条件的后台账号': 'No matching admin accounts',
  '没有符合条件的门店': 'No matching stores',
  '没有找到顾客，可点击“新建顾客”快速创建': 'No customer found. Select “New customer” to create one.',
  '没有找到用户': 'No users found',
  '每行：手机号,姓名,佣金比例。姓名和比例可留空，最多200行。': 'One per line: phone, name, commission rate. Name and rate are optional; maximum 200 lines.',
  '密码只会以安全哈希形式保存，创建后无法查看原密码。': 'Passwords are stored only as secure hashes and cannot be viewed after creation.',
  '名称': 'Name',
  '配送单号：': 'Delivery number:',
  '配送完成': 'Delivery completed',
  '配置登录身份、角色权限和所属门店': 'Configure login identity, role permissions, and assigned store.',
  '批准': 'Approve',
  '骑手已取餐': 'Rider picked up',
  '钱包充值': 'Wallet top-up',
  '钱包余额': 'Wallet balance',
  '请先添加菜品': 'Add a menu item first.',
  '请选择分类': 'Select a category',
  '全部角色': 'All roles',
  '全部门店': 'All stores',
  '全部收支': 'All transactions',
  '确认后余额会立即入账并生成不可删除的审计流水。请再次核对用户和金额。': 'The balance will be credited immediately and a permanent audit record will be created. Check the user and amount again.',
  '确认送达': 'Confirm delivery',
  '确认已付款': 'Confirm paid',
  '人工填写其他语言；留空则前台显示中文内容。': 'Enter translations manually. Blank fields use the Chinese storefront content.',
  '上移': 'Move up',
  '设置分类名称、顺序和可用状态': 'Set category name, order, and availability.',
  '申请编号：': 'Application ID:',
  '深夜食汤': 'Soup Can Thin',
  '审核': 'Review',
  '审核说明：': 'Review note:',
  '是否重复...': 'Checking for duplicates...',
  '收据': 'Receipt',
  '手机号会自动标准化并检查重复。用户之后可以使用相同手机号接收 OTP 登录。': 'The phone number is normalized and checked for duplicates. The user can later sign in by OTP with the same number.',
  '手机号批量注册代理': 'Bulk register agents by phone',
  '数量': 'Quantity',
  '搜索': 'Search',
  '搜索用户后选择发放对象': 'Search users and select recipients',
  '所有代理默认规则': 'Default rule for all agents',
  '添加': 'Add',
  '添加选项': 'Add option',
  '添加组': 'Add group',
  '通过': 'Approve',
  '通过并生成代理码': 'Approve and generate agent code',
  '推广码': 'Referral code',
  '完成前两步后选择菜品': 'Complete the first two steps before selecting menu items.',
  '位用户。系统会自动跳过超过每人限领或总发行量的记录。': 'users selected. Records exceeding per-user or total limits are skipped automatically.',
  '下一步：确认订单': 'Next: Confirm order',
  '下一步：选择菜品': 'Next: Select menu items',
  '下移': 'Move down',
  '线上已付款订单及已完成现金订单会自动计入营业收入。': 'Paid online orders and completed cash orders are included in operating income automatically.',
  '销售状态': 'Sales status',
  '新建顾客': 'New customer',
  '新建用户': 'New user',
  '新增佣金规则': 'Add commission rule',
  '新增账号': 'Add account',
  '修改菜品': 'Edit menu item',
  '修改原因': 'Reason for change',
  '选项': 'Option',
  '页，每页最多 50 位用户': 'pages, up to 50 users per page',
  '一次性代理码': 'One-time agent code',
  '已冲销': 'Reversed',
  '已存在，不能重复使用。': 'already exists and cannot be reused.',
  '已选择': 'Selected',
  '佣金': 'Commission',
  '有效期': 'Validity',
  '有效期至：': 'Valid until:',
  '余额': 'Balance',
  '余额：RM': 'Balance: RM',
  '预计送达：': 'Estimated delivery:',
  '原图最大 5MB，保存时上传；优先 WebP，必要时使用 JPG，输出不超过 500KB，并命名为': 'Original image: maximum 5 MB. Uploaded on save; WebP preferred, JPG fallback; output under 500 KB and named',
  '原因：': 'Reason:',
  '暂不分配': 'Unassigned',
  '暂无发放记录': 'No issue records',
  '暂无顾客': 'No customers',
  '暂无修改记录': 'No change history',
  '暂无优惠券活动': 'No coupon campaigns',
  '账号信息': 'Account information',
  '这个': 'this',
  '这里只翻译显示名称，ID、价格、单选/多选继续使用中文主数据。': 'Only display names are translated here. IDs, prices, and selection types continue to use the Chinese master data.',
  '正在加载用户资料': 'Loading user profile',
  '正在检查': 'Checking',
  '执行批量注册': 'Run bulk registration',
  '只记录系统订单以外的收入': 'Record only income outside system orders',
  '只看开支': 'Expenses only',
  '只看收入': 'Income only',
  '只显示一次，请立即安全发送给申请人。': 'Shown once only. Send it securely to the applicant now.',
  '重新加载': 'Reload',
  '重新生成代理码': 'Regenerate agent code',
  '注册信息': 'Registration information',
  '注册于': 'Registered',
  '自动': 'Automatic',
  'ID 只能使用英文字母、数字、下划线或短横线。': 'ID may contain only letters, numbers, underscores, or hyphens.',
  'km · 约': 'km · about',
  '菜单管理': 'Menu Management',
  '菜单加载失败': 'Failed to load menu',
  '处理中': 'Processing',
  '订单': 'Order',
  '订单加载失败': 'Failed to load orders',
  '订单详情加载失败': 'Failed to load order details',
  '订单状态已更新': 'Order status updated',
  '分钟': 'minutes',
  '更新于': 'Updated',
  '顾': 'C',
  '顾客加载失败': 'Failed to load customers',
  '后台所有固定界面文案会使用所选语言。业务数据与已填写内容不会被修改。': 'All fixed admin interface text uses the selected language. Business data and existing content are not changed.',
  '简体中文': 'Simplified Chinese',
  '减免金额 RM': 'Discount amount RM',
  '今日收支': 'Today’s income & expenses',
  '仅限首次下单使用': 'First order only',
  '进入页面后自动同步': 'Automatically synced when this page opens',
  '老板 / Manager': 'Owner / Manager',
  '门店加载失败': 'Failed to load stores',
  '全部': 'All',
  '确认发放': 'Confirm issue',
  '人工': 'Manual',
  '上一页': 'Previous page',
  '少辣 / 不要葱': 'Less spicy / no spring onion',
  '收据读取失败': 'Failed to read receipt',
  '收据图片不能超过 5MB': 'Receipt image cannot exceed 5 MB.',
  '收据只支持 JPG、PNG 或 WebP': 'Receipts support JPG, PNG, or WebP only.',
  '通用': 'General',
  '退出': 'Log out',
  '退出后台': 'Log out of admin',
  '未分配门店': 'No store assigned',
  '下架失败': 'Failed to deactivate',
  '下一页': 'Next page',
  '新用户欢迎券': 'New user welcome coupon',
  '新增后台账号': 'Add admin account',
  '新增门店': 'Add store',
  '修改记录': 'Change history',
  '修改配送安排': 'Edit delivery assignment',
  '选项 ID': 'Option ID',
  '选项名称': 'Option name',
  '选项译名': 'Option translation',
  '选择后台系统的显示语言。设置会保存在当前设备。': 'Choose the display language for the admin system. Your preference is saved on this device.',
  '已存在': 'Already exists',
  '已选择新图片，保存后上传生效：': 'New image selected. It will be uploaded when saved:',
  '英文': 'English',
  '用': 'Use',
  '用户': 'User',
  '用户加载失败': 'Failed to load users',
  '用于前台选择规格、加料和自动计算加价。': 'Used on the storefront to select options and add-ons and calculate price adjustments.',
  '语言': 'Language',
  '语言已切换': 'Language updated',
  '展开侧栏': 'Expand sidebar',
  '长期': 'Long term',
  '长期有效': 'No expiry',
  '账号加载失败': 'Failed to load accounts',
  '账号状态更新失败': 'Failed to update account status',
  '折叠侧栏': 'Collapse sidebar',
  '正在创建...': 'Creating...',
  '正在发放': 'Issuing',
  'JPG、PNG、WebP，最大 5MB': 'JPG, PNG, or WebP, maximum 5 MB',
  '不能删除当前登录账号': 'You cannot delete the account currently signed in.',
  '不能停用当前登录账号': 'You cannot disable the account currently signed in.',
  '不能移除当前登录账号的管理权限': 'You cannot remove administrative access from the account currently signed in.',
  '不支持的操作': 'Unsupported action',
  '不支持的查重字段': 'Unsupported duplicate-check field',
  '菜单图片不能超过 500KB': 'Menu images cannot exceed 500 KB.',
  '菜单图片只支持 WebP 或 JPG': 'Menu images support WebP or JPG only.',
  '菜品 ID 必须是正整数': 'Menu item ID must be a positive integer.',
  '菜品不存在': 'Menu item not found',
  '菜品状态未更新，请刷新后重试': 'Menu item status was not updated. Refresh and try again.',
  '参考编号不能超过 100 个字符': 'Reference number cannot exceed 100 characters.',
  '操作不正确': 'Invalid action',
  '查询范围不能超过 370 天': 'The query range cannot exceed 370 days.',
  '充值金额需介于 RM 0.01 至 RM 100000': 'Top-up amount must be between RM 0.01 and RM 100,000.',
  '充值请求编号不正确': 'Invalid top-up request ID',
  '充值已拒绝': 'Top-up rejected',
  '充值已通过并入账': 'Top-up approved and credited',
  '初始化 token 不正确': 'Invalid setup token',
  '初始活动状态不正确': 'Invalid initial campaign status',
  '代理码仅显示一次，请立即安全发送给申请人': 'The agent code is shown once only. Send it securely to the applicant now.',
  '代理专属佣金': 'Agent-specific commission',
  '代理状态不正确': 'Invalid agent status',
  "待审核 Touch 'n Go eWallet 订单不存在或已处理": "The pending Touch 'n Go eWallet order does not exist or has already been processed.",
  '待审核充值不存在或已处理': 'The pending top-up does not exist or has already been processed.',
  '单次最多向 500 位用户发券': 'Coupons can be issued to at most 500 users at a time.',
  '当前菜品缺少分类，无法排序': 'This menu item has no category and cannot be reordered.',
  '当前订单不能标记缺货': 'This order cannot be marked out of stock.',
  '当前付款状态不允许更正为转账': 'The current payment status cannot be changed to bank transfer.',
  '当前配送任务不能开始配送': 'This delivery task cannot be started.',
  '当前配送任务不能确认送达': 'This delivery task cannot be marked delivered.',
  '当前账号尚未分配门店，请联系管理员': 'No store is assigned to this account. Contact an administrator.',
  '店内配送需要填写配送员姓名': 'A rider name is required for in-house delivery.',
  '调整金额不正确': 'Invalid adjustment amount',
  '订单不存在': 'Order not found',
  '订单内容不能为空': 'Order contents cannot be empty.',
  '订单修改记录写入失败': 'Failed to save order change history',
  '订单营业收入': 'Order operating income',
  '订单状态不正确': 'Invalid order status',
  '订单状态已变化，请刷新后重试': 'Order status has changed. Refresh and try again.',
  '发生时间不正确': 'Invalid transaction time',
  '分类必填': 'Category is required.',
  '分类不存在': 'Category not found',
  '分类名称必填': 'Category name is required.',
  '分类名称不能超过 40 个字符': 'Category name cannot exceed 40 characters.',
  '付款方式不正确': 'Invalid payment method',
  '该分类下还有菜品，请先调整菜品分类后再删除': 'This category still contains menu items. Move them to another category before deleting it.',
  '该申请当前不能通过': 'This application cannot currently be approved.',
  '该手机号已存在，请直接选择已有顾客': 'This phone number already exists. Select the existing customer.',
  '该手机号已经是代理': 'This phone number is already registered as an agent.',
  '该提现申请当前不能审核': 'This withdrawal request cannot currently be reviewed.',
  '该账目已经冲销': 'This transaction has already been reversed.',
  '顾客不存在': 'Customer not found',
  '顾客姓名不能超过 60 个字符': 'Customer name cannot exceed 60 characters.',
  '管理员账号创建失败': 'Failed to create administrator account',
  '管理员账号已经初始化': 'Administrator account has already been initialized.',
  '规格/加料必须是数组': 'Options/add-ons must be an array.',
  '后台 session secret 未配置': 'Admin session secret is not configured.',
  '后台操作失败': 'Admin action failed',
  '后台代客下单目前只支持现金/到店支付': 'Admin-created customer orders currently support cash / pay-in-store only.',
  '会员账号创建失败': 'Failed to create member account',
  '活动状态不正确': 'Invalid campaign status',
  '价格必填': 'Price is required.',
  '价格格式不正确': 'Invalid price format',
  '领取后有效天数不正确': 'Invalid validity period after claim',
  '没有撤销优惠券权限': 'You do not have permission to revoke coupons.',
  '没有发券权限': 'You do not have permission to issue coupons.',
  '没有可更新的字段': 'There are no fields to update.',
  '没有权限访问此功能': 'You do not have permission to access this feature.',
  '没有权限访问其他门店': 'You do not have permission to access other stores.',
  '每人限领数量不正确': 'Invalid per-user claim limit',
  '门店 ID 必填': 'Store ID is required.',
  '门店 ID 已存在': 'Store ID already exists.',
  '门店 ID 只能使用小写字母、数字、横线或下划线': 'Store ID may contain lowercase letters, numbers, hyphens, or underscores only.',
  '门店不存在': 'Store not found',
  '门店地址必填': 'Store address is required.',
  '门店地址不能超过 240 个字符': 'Store address cannot exceed 240 characters.',
  '门店更新失败': 'Failed to update store',
  '门店名称必填': 'Store name is required.',
  '门店名称不能超过 80 个字符': 'Store name cannot exceed 80 characters.',
  '门店新增失败': 'Failed to add store',
  '密码至少需要 8 位': 'Password must be at least 8 characters.',
  '默认佣金': 'Default commission',
  "目前只支持更正为 Touch 'n Go 转账": "Only correction to Touch 'n Go transfer is currently supported.",
  '排序必须是整数': 'Sort order must be an integer.',
  '配送操作不正确': 'Invalid delivery action',
  '配送成本不正确': 'Invalid delivery cost',
  '配送已经开始，不能重新分配': 'Delivery has started and cannot be reassigned.',
  '配送员电话格式不正确': 'Invalid rider phone number format',
  '请输入有效金额': 'Enter a valid amount.',
  '请提供至少一个手机号': 'Provide at least one phone number.',
  '请填写 1-80 字的优惠券名称': 'Enter a coupon name between 1 and 80 characters.',
  '请填写 2-300 字的充值原因': 'Enter a top-up reason between 2 and 300 characters.',
  '请填写撤销原因': 'Enter a revocation reason.',
  '请填写冲销原因': 'Enter a reversal reason.',
  '请填写发放原因': 'Enter an issue reason.',
  '请填写顾客姓名': 'Enter the customer name.',
  '请填写审核原因': 'Enter a review reason.',
  '请先安排配送': 'Arrange delivery first.',
  '请先登录后台': 'Sign in to admin first.',
  '请先填写有效编码，编码只能包含字母、数字、点、下划线或横线': 'Enter a valid code using letters, numbers, periods, underscores, or hyphens.',
  '请选择充值来源': 'Select a top-up source.',
  '请选择充值用户': 'Select a user to top up.',
  '请选择配送方式': 'Select a delivery method.',
  '请选择优惠券': 'Select a coupon.',
  '请选择有效的上架分类': 'Select an active category.',
  '请选择有效分类': 'Select a valid category.',
  '请选择至少一位用户': 'Select at least one user.',
  '请至少选择一个适用范围': 'Select at least one eligibility option.',
  '券码需为 3-32 位大写字母、数字、下划线或横线': 'Coupon code must be 3–32 uppercase letters, numbers, underscores, or hyphens.',
  '缺少操作': 'Action is required.',
  '缺少代理记录': 'Agent record is required.',
  '缺少订单 ID': 'Order ID is required.',
  '缺少付款修改记录': 'Payment change record is required.',
  '缺少门店 ID': 'Store ID is required.',
  '缺少申请记录': 'Application record is required.',
  '缺少有效菜品 ID': 'A valid menu item ID is required.',
  '缺少有效分类 ID': 'A valid category ID is required.',
  '缺少账号 ID': 'Account ID is required.',
  '缺少账目 ID': 'Transaction ID is required.',
  '日期范围不正确': 'Invalid date range',
  '日期格式不正确': 'Invalid date format',
  '审核操作不正确': 'Invalid review action',
  '审核失败': 'Review failed',
  '收据图片为空': 'Receipt image is empty.',
  '收支类型不正确': 'Invalid transaction type',
  '数据库尚未更新财务模块字段 assigned_branch_id，请先执行最新版 supabase-schema.sql。': 'The database is missing the finance field assigned_branch_id. Apply the latest supabase-schema.sql first.',
  '所选门店不可用或未启用': 'The selected store is unavailable or disabled.',
  '所选用户均已达到领取上限': 'All selected users have reached the claim limit.',
  '提现审核状态不正确': 'Invalid withdrawal review status',
  '停用代理时必须填写原因': 'A reason is required when suspending an agent.',
  '图片链接': 'Image URL',
  '图片数据为空': 'Image data is empty.',
  '外卖订单不存在': 'Delivery order not found',
  '系统订单': 'System order',
  '已完成或已取消订单不能修改支付方式': 'Payment method cannot be changed for completed or cancelled orders.',
  '佣金比例不正确': 'Invalid commission rate',
  '佣金比例应为0至100': 'Commission rate must be between 0 and 100.',
  '佣金调整必须填写原因': 'A reason is required for commission adjustments.',
  '用户不存在': 'User not found',
  '优惠类型不正确': 'Invalid discount type',
  '优惠券不存在或未上线': 'Coupon not found or not published.',
  '优惠券创建失败': 'Failed to create coupon',
  '优惠券活动已结束': 'Coupon campaign has ended.',
  '优惠券已达到总发行上限': 'Coupon has reached its total issue limit.',
  '优惠值不正确': 'Invalid discount value',
  '预计取餐时间': 'Estimated pickup time',
  '预计送达时间': 'Estimated delivery time',
  '预计送达时间必须晚于预计取餐时间': 'Estimated delivery time must be later than estimated pickup time.',
  '账号不存在': 'Account not found',
  '账号创建失败': 'Failed to create account',
  '账号更新失败': 'Failed to update account',
  '账号或密码不正确': 'Incorrect account or password',
  '账号角色不正确': 'Invalid account role',
  '账号需为 3-32 位，可包含小写字母、数字、点、下划线或横线': 'Account must be 3–32 characters using lowercase letters, numbers, periods, underscores, or hyphens.',
  '账目不存在': 'Transaction not found',
  '只有待制作订单可以开始制作': 'Only orders waiting for preparation can be started.',
  '只有店长或管理员可以审核和冲销账目': 'Only store managers or administrators can review and reverse transactions.',
  '只有管理员或老板可以创建优惠券': 'Only administrators or owners can create coupons.',
  '只有管理员或老板可以更改活动状态': 'Only administrators or owners can change campaign status.',
  '只有管理员或老板可以审核付款截图': 'Only administrators or owners can review payment proof.',
  '只有管理员或老板可以直接充值': 'Only administrators or owners can apply direct top-ups.',
  '只有后台代下单可以更正支付方式': 'Only admin-created orders can have their payment method corrected.',
  '只有老板或管理员可以执行该操作': 'Only owners or administrators can perform this action.',
  '只有制作中订单可以标记完成': 'Only orders being prepared can be marked complete.',
  '至少需要保留一个启用的管理员或老板账号': 'At least one enabled administrator or owner account must remain.',
  '至少需要保留一个启用门店': 'At least one enabled store must remain.',
  '总发行量不正确': 'Invalid total issue limit',
  '最低订单金额不正确': 'Invalid minimum order amount',
  '最低消费金额不正确': 'Invalid minimum spending amount',
  'Supabase 服务密钥时间无效：JWT 签发时间在未来。请检查 SUPABASE_SERVICE_ROLE_KEY 是否正确、运行机器时间是否同步，然后重启后台服务。': 'The Supabase service key time is invalid: the JWT issue time is in the future. Check SUPABASE_SERVICE_ROLE_KEY and the server clock, then restart the admin service.',
};
